Repository firesim/firesim, pull requests merged in 2022-05, with the labels that each got.

#1042 Add Python typing to all files + Cleanup based off it
  .github/workflows/firesim-run-tests.yml
  deploy/awstools/afitools.py
  deploy/awstools/aws_setup.py
  deploy/awstools/awstools.py
  deploy/buildtools/bitbuilder.py
  deploy/buildtools/buildconfig.py
  deploy/buildtools/buildconfigfile.py
  deploy/buildtools/buildfarm.py
  deploy/firesim
  deploy/runtools/firesim_topology_core.py
  deploy/runtools/firesim_topology_elements.py
  deploy/runtools/firesim_topology_with_passes.py
  deploy/runtools/run_farm.py
  deploy/runtools/runtime_config.py
  deploy/runtools/switch_model_config.py
  deploy/runtools/user_topology.py
  deploy/runtools/utils.py
  deploy/runtools/workload.py
  deploy/tests/awstools/test_awstools.py
  deploy/tests/conftest.py
  deploy/tests/test_firesim_top.py
  deploy/tests/test_yaml_api.py
  deploy/util/streamlogger.py
Labels: changelog:changed, ci:fpga-deploy

#1036 [docs] Update Setting-up-your-Manager-Instance.rst to match new EC2 launch GUI
  docs/Initial-Setup/Setting-up-your-Manager-Instance.rst
Labels: changelog:changed

#1049 Provide AWS creds when cleaning up after a failed manager initialization
  .github/actions/change-workflow-instance-states/action.yml
  .github/workflows/firesim-run-tests.yml
Labels: changelog:omit

#1053 Improve error messaging in target clock analysis
  sim/midas/src/main/scala/midas/passes/TargetClockAnalysis.scala
Labels: changelog:added

#1031 Adding Termination Bridge with target defined conditions and messaging.
  sim/midas/src/main/cc/bridges/termination.cc
  sim/midas/src/main/cc/bridges/termination.h
  sim/midas/src/main/scala/midas/widgets/TerminationBridge.scala
  sim/src/main/cc/midasexamples/Driver.cc
  sim/src/main/cc/midasexamples/TerminationModule.h
  sim/src/main/scala/midasexamples/Termination.scala
  sim/src/test/scala/midasexamples/TutorialSuite.scala
Labels: changelog:added

#1056 VSCode Integration for Scala Development
  build-setup-nolog.sh
  docs/Developer-Docs/VSCode-Integration.rst
  docs/index.rst
  sim/.gitignore
  sim/.vscode/sbt-launch.sh
  sim/.vscode/settings.json
  sim/project/plugins.sbt
Labels: changelog:added

#1060 Scala Source Formatting via Scalafmt
  .github/scripts/run-scalafmt-check.py
  .github/workflows/firesim-run-tests.yml
  sim/.scalafmt.conf
  sim/midas/src/main/scala/junctions/MultiWidthFifo.scala
  sim/project/plugins.sbt
  sim/target-agnostic.mk
Labels: changelog:added
