Repository firesim/firesim, pull requests merged in 2022-03, with the labels that each got.

#982 update test_amis.json after #977 failed to
  deploy/tests/test_amis.json
Labels: changelog:fixed

#966 Issue template update
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/workflows/firesim-run-tests.yml
Labels: changelog:omit

#856 Add AMI flag to awstools CLI
  deploy/awstools/awstools.py
Labels: enhancement

#985 Rewrite yaml api tests for where-to-build
  .github/scripts/run-yaml-api-tests.py
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-aws-ec2-inst-type/sample_config_build.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-aws-ec2-inst-type/sample_config_build_farm.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-aws-ec2-inst-type/sample_config_build_recipes.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-aws-ec2-no-args/sample_config_build.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-aws-ec2-no-args/sample_config_build_farm.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-aws-ec2-no-args/sample_config_build_recipes.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-build-section/sample_config_build.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-build-section/sample_config_build_farm.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-build-section/sample_config_build_recipes.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-buildfarm-type/sample_config_build.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-buildfarm-type/sample_config_build_farm.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-buildfarm-type/sample_config_build_recipes.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-unmanaged-no-args/sample_config_build.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-unmanaged-no-args/sample_config_build_farm.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-unmanaged-no-args/sample_config_build_recipes.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-unmanaged-no-hosts/sample_config_build.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-unmanaged-no-hosts/sample_config_build_farm.yaml
  .github/scripts/yaml-tests/failing-buildafi-files/invalid-unmanaged-no-hosts/sample_config_build_recipes.yaml
  .github/scripts/yaml-tests/failing-runtime-files/hwdb-invalid-afi/sample_config_hwdb.yaml
  .github/scripts/yaml-tests/failing-runtime-files/hwdb-invalid-afi/sample_config_runtime.yaml
  .github/scripts/yaml-tests/failing-runtime-files/runtime-invalid-hwconfig/sample_config_hwdb.yaml
  .github/scripts/yaml-tests/failing-runtime-files/runtime-invalid-hwconfig/sample_config_runtime.yaml
  .github/scripts/yaml-tests/failing-runtime-files/runtime-invalid-topology/sample_config_hwdb.yaml
  .github/scripts/yaml-tests/failing-runtime-files/runtime-invalid-topology/sample_config_runtime.yaml
  .github/scripts/yaml-tests/failing-runtime-files/runtime-invalid-workloadname/sample_config_hwdb.yaml
  .github/scripts/yaml-tests/failing-runtime-files/runtime-invalid-workloadname/sample_config_runtime.yaml
  .github/workflows/firesim-run-tests.yml
  deploy/.gitignore
  deploy/firesim
  deploy/runtools/runtime_config.py
  deploy/tests/awstools/test_awstools.py
  deploy/tests/conftest.py
  deploy/tests/test_firesim_top.py
  deploy/tests/test_yaml_api.py
  scripts/machine-launch-script.sh
Labels: changelog:omit

#988 update libdwarf submodule url
  .gitmodules
Labels: Please Backport, changelog:fixed

#990 fix first clone setup fast script
  scripts/first-clone-setup-fast.sh
Labels: changelog:fixed

#991 Use pagination for boto3 calls in the manager
  deploy/awstools/afitools.py
  deploy/awstools/awstools.py
  deploy/tests/awstools/test_awstools.py
  deploy/tests/test_scripts.py
  scripts/machine-launch-script.sh
Labels: Please Backport, changelog:fixed, ci:fpga-deploy

#999 Fix synthesized assertions stop-printf pair detection
  sim/midas/src/main/scala/midas/passes/HoistStopAndPrintfEnables.scala
  sim/midas/src/main/scala/midas/passes/MidasTransforms.scala
Labels: Please Backport, changelog:fixed

#1002 Retroactively slurp in CI changes to 1.13.x
  .github/scripts/cull-old-ci-instances.py
  .github/scripts/run-linux-poweroff.py
  .github/workflows/firesim-run-tests.yml
Labels: changelog:omit
