Repository firesim/firesim, pull requests merged in 2022-02, with the labels that each got.

#921 Workaround `rsync_project` `exclude` flag issue
  deploy/buildtools/buildafi.py
Labels: bug

#950 Replace call to fpga_pci_init with fpga_mgmt_init
  .github/scripts/run-linux-poweroff.py
  sim/midas/src/main/cc/simif_f1.cc
Labels: Please Backport, changelog:fixed

#948 update PULL_REQUEST_TEMPLATE.md for main branch [skip ci]
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog:omit

#954 [ci] Filter jobs based on changed files
  .github/workflows/firesim-run-tests.yml
Labels: changelog:omit

#957 Add --skip-validate to build-setup GH action
  .github/actions/buildsetup/action.yml
  regression/aws-ec2-tests/launch-setup-manager-instance.sh
Labels: Please Backport, changelog:omit

#962 Fix cull instances CI workflow
  .github/scripts/cull-old-ci-instances.py
Labels: changelog:fixed

#965 Update autocounter-csv-format.csv for proper spelling
  docs/Advanced-Usage/Debugging-and-Profiling-on-FPGA/autocounter-csv-format.csv
Labels: changelog:fixed

#959 [ci] Have CI workflow run on 1.<version>.x branches
  .github/workflows/firesim-run-tests.yml
Labels: changelog:omit

#953 [ci] Put FPGA deployment on a tag ci:fpga-deploy
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/firesim-run-tests.yml
Labels: changelog:omit, ci:fpga-deploy

#969 Update changelog for 1.13.1
  CHANGELOG.md
Labels: Please Backport, changelog:omit

#972 Update Setting-up-your-Manager-Instance.rst
  docs/Initial-Setup/Setting-up-your-Manager-Instance.rst
Labels: Please Backport, changelog:fixed

#974 Update CHANGELOG.md for 1.13.2 release
  CHANGELOG.md
Labels: Please Backport, changelog:omit

#977 Update AMI string in deploy
  CHANGELOG.md
  deploy/awstools/awstools.py
Labels: Please Backport, changelog:fixed
