Repository firesim/firesim, pull requests merged in 2022-11, with the labels that each got.

#1288 manager: fix string interpolation in buildconfigfile
  deploy/buildtools/buildconfigfile.py
Labels: changelog:fixed

#1294 fixed runners for midas / targetutils tests
  .github/workflows/firesim-run-tests.yml
Labels: changelog:omit

#1295 Fix SimUtils tests
  sim/midas/src/test/scala/midas/core/SimUtilsSpec.scala
Labels: changelog:omit

#1296 Fix Reset Synchronizer For InitValues == 0
  sim/midas/src/main/scala/midas/platform/xilinx/ResetSynchronizer.scala
Labels: changelog:fixed

#1298 Fix MCRAMs optimization with more strict FPGA backend passes
  sim/midas/src/main/scala/midas/stage/GoldenGateCompilerPhase.scala
Labels: changelog:fixed

#1302 Fix C++ compiler warnings
  sim/firesim-lib/src/main/cc/bridges/blockdev.cc
  sim/firesim-lib/src/main/cc/bridges/blockdev.h
  sim/firesim-lib/src/main/cc/bridges/simplenic.cc
  sim/firesim-lib/src/main/cc/bridges/simplenic.h
  sim/firesim-lib/src/main/cc/bridges/tracerv.cc
  sim/firesim-lib/src/main/cc/bridges/uart.cc
  sim/firesim-lib/src/main/cc/fesvr/firesim_tsi.cc
  sim/firesim-lib/src/main/cc/fesvr/firesim_tsi.h
  sim/midas/src/main/cc/bridges/heartbeat.cc
  sim/midas/src/main/cc/bridges/reset_pulse.cc
  sim/midas/src/main/cc/bridges/reset_pulse.h
  sim/midas/src/main/cc/bridges/synthesized_assertions.cc
  sim/midas/src/main/cc/bridges/synthesized_assertions.h
  sim/midas/src/main/cc/simif.h
  sim/midas/src/main/cc/simif_emul.cc
  sim/midas/src/main/cc/simif_emul.h
  sim/src/main/cc/fasedtests/fasedtests_top.cc
  sim/src/main/cc/firesim/firesim_top.cc
  sim/src/main/cc/midasexamples/AssertModule.h
  sim/src/main/cc/midasexamples/AssertTorture.h
  sim/src/main/cc/midasexamples/MulticlockAssertModule.h
  sim/src/main/cc/midasexamples/TriggerWiringModule.h
  sim/src/main/cc/midasexamples/simif_peek_poke.cc
  sim/src/main/makefrag/firesim/Makefrag
Labels: changelog:omit

#1304 AutoCounter: Add cinttypes to autocounter.h for format specifier bug
  sim/midas/src/main/cc/bridges/autocounter.cc
Labels: changelog:fixed

#1300 Regenerate AGFIs to fix references to removed FXXMHz classes
  .github/workflows/firesim-run-tests.yml
  deploy/sample-backup-configs/sample_config_hwdb.yaml
Labels: changelog:omit, ci:fpga-deploy

#1306 Add apply method that takes ReferenceTarget parameter in RAMStyleHint
  sim/midas/targetutils/src/main/scala/midas/xdc/RAMStyleHint.scala
  sim/midas/targetutils/src/test/scala/RAMStyleHintSpec.scala
Labels: changelog:added

#1308 Move XDC circuit paths to config
  sim/midas/src/main/scala/midas/Config.scala
  sim/midas/src/main/scala/midas/platform/F1Shim.scala
  sim/midas/src/main/scala/midas/platform/PlatformShim.scala
  sim/midas/src/main/scala/midas/platform/VitisShim.scala
Labels: changelog:changed

#1309 Remove raw pointers from bridge port address creation
  sim/firesim-lib/src/main/cc/bridges/blockdev.cc
  sim/firesim-lib/src/main/cc/bridges/blockdev.h
  sim/firesim-lib/src/main/cc/bridges/serial.cc
  sim/firesim-lib/src/main/cc/bridges/serial.h
  sim/firesim-lib/src/main/cc/bridges/simplenic.cc
  sim/firesim-lib/src/main/cc/bridges/simplenic.h
  sim/firesim-lib/src/main/cc/bridges/tracerv.cc
  sim/firesim-lib/src/main/cc/bridges/tracerv.h
  sim/firesim-lib/src/main/cc/bridges/uart.cc
  sim/firesim-lib/src/main/cc/bridges/uart.h
  sim/midas/src/main/cc/bridges/autocounter.cc
  sim/midas/src/main/cc/bridges/autocounter.h
  sim/midas/src/main/cc/bridges/plusargs.cc
  sim/midas/src/main/cc/bridges/plusargs.h
  sim/midas/src/main/cc/bridges/reset_pulse.cc
  sim/midas/src/main/cc/bridges/reset_pulse.h
  sim/midas/src/main/cc/bridges/synthesized_assertions.cc
  sim/midas/src/main/cc/bridges/synthesized_assertions.h
  sim/midas/src/main/cc/bridges/synthesized_prints.cc
  sim/midas/src/main/cc/bridges/synthesized_prints.h
  sim/midas/src/main/cc/simif.cc
  sim/midas/src/main/cc/simif.h
  sim/midas/src/main/scala/midas/widgets/Lib.scala
  sim/src/main/cc/firesim/firesim_top.cc
  sim/src/main/cc/midasexamples/AssertModule.h
  sim/src/main/cc/midasexamples/AssertTorture.h
  sim/src/main/cc/midasexamples/MulticlockAssertModule.h
  sim/src/main/cc/midasexamples/TerminationModule.h
  sim/src/main/cc/midasexamples/TriggerWiringModule.h
  sim/src/main/cc/midasexamples/simif_peek_poke.cc
  sim/src/main/cc/midasexamples/simif_peek_poke.h
Labels: changelog:changed
