Repository firesim/firesim, pull requests merged in 2022-09, with the labels that each got.

#1184 bridges: Remove references to DMA_X in driver sources
  sim/firesim-lib/src/main/cc/bridges/dromajo.cc
  sim/firesim-lib/src/main/cc/bridges/simplenic.cc
  sim/firesim-lib/src/main/cc/bridges/tracerv.cc
  sim/midas/src/main/cc/bridges/bridge_driver.h
  sim/midas/src/main/cc/bridges/synthesized_prints.h
Labels: changelog:changed

#1194 Adding ci job to test f1 driver build
  .github/scripts/build-f1-driver.py
  .github/workflows/firesim-run-tests.yml
Labels: changelog:omit

#1196 Metasimulation: remove dependency on fesvr for ucontext
  sim/midas/src/main/cc/Makefile
  sim/midas/src/main/cc/emul/context.cc
  sim/midas/src/main/cc/emul/context.h
  sim/midas/src/main/cc/emul/verilator-harness.cc
  sim/midas/src/main/cc/simif_emul.cc
  sim/src/main/makefrag/fasedtests/Makefrag
  sim/src/main/makefrag/midasexamples/Makefrag
Labels: changelog:changed

#1199 Fixed compiler error caused by private destructor
  sim/midas/src/main/cc/bridges/fased_memory_timing_model.h
  sim/midas/src/main/cc/bridges/fpga_model.h
  sim/src/main/cc/fasedtests/fasedtests_top.h
Labels: changelog:omit

#1204 Allocated memory using MAP_NORESERVE
  sim/midas/src/main/cc/emul/mm.cc
Labels: changelog:omit

#1198 Added debug flags to CI
  .github/CI_README.md
  .github/scripts/setup-manager-self-hosted.py
  .github/workflows/firesim-run-tests.yml
Labels: changelog:omit

#1202 Removed the Fame1Instances transformation
  sim/midas/src/main/scala/midas/models/dram/FASEDMemoryTimingModel.scala
  sim/midas/src/main/scala/midas/models/dram/Util.scala
  sim/midas/src/main/scala/midas/passes/Fame1Transform.scala
  sim/midas/src/main/scala/midas/passes/MidasTransforms.scala
  sim/midas/src/main/scala/midas/passes/SimulationMapping.scala
  sim/midas/src/main/scala/midas/passes/fame/Annotations.scala
  sim/midas/src/main/scala/midas/passes/fame/FAMEDefaults.scala
  sim/midas/src/main/scala/midas/passes/fame/FAMETransform.scala
  sim/midas/src/main/scala/midas/passes/fame/FAMEUtils.scala
  sim/midas/src/main/scala/midas/passes/fame/InferModelPorts.scala
  sim/midas/src/main/scala/midas/passes/fame/TrivialChannelExcision.scala
  sim/midas/src/main/scala/midas/passes/xilinx/package.scala
Labels: changelog:removed

#1210 Fix CI conda-lock check
  .github/workflows/firesim-run-tests.yml
Labels: changelog:omit

#1211 mm: Properly comment post-#endif tokens
  sim/midas/src/main/cc/emul/mm.h
Labels: changelog:omit

#1212 Fix FireSim library setup
  build-setup-nolog.sh
Labels: bug, changelog:omit

#1217 Fix self-hosted runner checkout
  .github/workflows/firesim-run-tests.yml
Labels: bug, ci:fpga-deploy

#1221 Introduced trait to represent the interface to channel ports
  sim/midas/src/main/scala/midas/core/FPGATop.scala
  sim/midas/src/main/scala/midas/core/SimWrapper.scala
  sim/midas/src/main/scala/midas/widgets/Bridge.scala
  sim/midas/src/main/scala/midas/widgets/ChannelizedHostPort.scala
  sim/midas/src/main/scala/midas/widgets/ClockBridge.scala
  sim/midas/src/main/scala/midas/widgets/HostPort.scala
Labels: changelog:omit

#923 Bypass manual input on `buildbitstream` cancellation
  .gitattributes
  deploy/buildtools/buildconfigfile.py
  deploy/firesim
  docs/Advanced-Usage/Manager/HELP_OUTPUT
  docs/Advanced-Usage/Manager/Manager-Tasks.rst
Labels: enhancement

#1228 improved error messages in ci, fixed catching failed inst
  .github/actions/change-workflow-instance-states/action.yml
  .github/scripts/common.py
  .github/workflows/firesim-run-tests.yml
Labels: changelog:omit

#1130 Add warn_only to vivado builds + Postpone error until all builds complete
  deploy/buildtools/bitbuilder.py
  deploy/firesim
Labels: bug, Please Backport, changelog:fixed

#1227 manager: Cast AWS IDs to string in shareagfi
  deploy/awstools/afitools.py
Labels: changelog:fixed

#1191 Support FPGA-managed AXI4/DMA in metasimulation
  deploy/sample-backup-configs/sample_config_hwdb.yaml
  sim/midas/src/main/cc/bridges/cpu_managed_stream.cc
  sim/midas/src/main/cc/bridges/cpu_managed_stream.h
  sim/midas/src/main/cc/bridges/synthesized_prints.h
  sim/midas/src/main/cc/emul/vcs-harness.cc
  sim/midas/src/main/cc/emul/verilator-harness.cc
  sim/midas/src/main/cc/simif_emul.cc
  sim/midas/src/main/cc/simif_emul.h
  sim/midas/src/main/cc/simif_f1.cc
  sim/midas/src/main/cc/simif_f1.h
  sim/midas/src/main/scala/midas/Config.scala
  sim/midas/src/main/scala/midas/core/CPUManagedStreamEngine.scala
  sim/midas/src/main/scala/midas/core/FPGAManagedStreamEngine.scala
  sim/midas/src/main/scala/midas/core/FPGATop.scala
  sim/midas/src/main/scala/midas/core/StreamEngine.scala
  sim/midas/src/main/scala/midas/platform/F1Shim.scala
  sim/midas/src/main/scala/midas/platform/VitisShim.scala
  sim/midas/src/main/scala/midas/widgets/PrintBridge.scala
  sim/midas/src/main/verilog/vcs_top.v
  sim/midas/src/main/verilog/verilator_top.sv
  sim/src/main/scala/midasexamples/Config.scala
  sim/src/test/scala/midasexamples/TutorialSuite.scala
Labels: changelog:added, ci:fpga-deploy

#1223 Removed the in-memory bridge annotation
  sim/midas/src/main/scala/midas/passes/AssertionSynthesis.scala
  sim/midas/src/main/scala/midas/passes/AutoCounterTransform.scala
  sim/midas/src/main/scala/midas/passes/PrintSynthesis.scala
  sim/midas/src/main/scala/midas/passes/UpdateBridgeClockInfo.scala
  sim/midas/src/main/scala/midas/widgets/BridgeAnnotations.scala
  sim/midas/src/main/scala/midas/widgets/ClockBridge.scala
Labels: changelog:removed

#1224 Removed the clock bridge annotation
  sim/midas/src/main/scala/midas/passes/ExtractBridges.scala
  sim/midas/src/main/scala/midas/widgets/Bridge.scala
  sim/midas/src/main/scala/midas/widgets/BridgeAnnotations.scala
  sim/midas/src/main/scala/midas/widgets/ClockBridge.scala
Labels: changelog:removed

#1213 Rename conda requirements files
  .gitattributes
  .github/workflows/firesim-run-tests.yml
  build-setup-nolog.sh
  conda-reqs.conda-lock.yml
  conda-reqs.yaml
Labels: enhancement, changelog:omit

#1238 build-setup: exclude conda-env from ctags
  .ctagsignore
  build-setup-nolog.sh
Labels: changelog:omit

#1237 Clarify exit code for `builtbitstream` in docs
  docs/Advanced-Usage/Manager/Manager-Tasks.rst
Labels: changelog:omit
