Repository firesim/firesim, pull requests merged in 2022-07, with the labels that each got.

#1114 add firesim builddriver command; plus a few metasim fixes and doc updates
  deploy/firesim
  deploy/runtools/firesim_topology_with_passes.py
  deploy/runtools/runtime_config.py
  docs/Advanced-Usage/Debugging-in-Software/RTL-Simulation.rst
  docs/Advanced-Usage/Manager/HELP_OUTPUT
  docs/Advanced-Usage/Manager/Manager-Configuration-Files.rst
  docs/Advanced-Usage/Manager/Manager-Tasks.rst
Labels: changelog:added

#1121 Don't use tsnyder conda channel in production machine-launch-script.sh
  scripts/machine-launch-script.sh
Labels: changelog:changed

#1122 Update CHANGELOG.md for 1.14.1 release
  CHANGELOG.md
  deploy/runtools/firesim_topology_core.py
Labels: changelog:omit, ci:fpga-deploy

#1123 Run CI
  deploy/awstools/afitools.py
Labels: changelog:omit, ci:fpga-deploy

#1125 docs: fix aws_setup.py reference
  docs/Initial-Setup/Configuring-Required-Infrastructure-in-Your-AWS-Account.rst
Labels: changelog:omit

#1129 Added missing return in `tracerv_t::process_tokens` to fix UB
  sim/firesim-lib/src/main/cc/bridges/tracerv.cc
Labels: changelog:fixed

#1131 CI: print ScalaTest stdout as it is running
  .github/scripts/run-scala-test.py
Labels: changelog:omit

#1143 add config_build_recipes.yaml to run_yamls pytest fixture
  deploy/tests/test_yaml_api.py
Labels: Please Backport, changelog:fixed

#1137 Fix mount files ownership
  deploy/runtools/firesim_topology_elements.py
Labels: bug, changelog:fixed, ci:fpga-deploy

#1146 Deinit Chipyard's FireSim submodule under FireSim-as-top
  build-setup-nolog.sh
Labels: changelog:fixed

#1141 Allowed bridge parameters to be serialized
  sim/midas/src/main/scala/midas/passes/AssertionSynthesis.scala
  sim/midas/src/main/scala/midas/passes/AutoCounterTransform.scala
  sim/midas/src/main/scala/midas/passes/PrintSynthesis.scala
  sim/midas/src/main/scala/midas/widgets/AssertBridge.scala
  sim/midas/src/main/scala/midas/widgets/AutoCounterBridge.scala
  sim/midas/src/main/scala/midas/widgets/ClockBridge.scala
  sim/midas/src/main/scala/midas/widgets/PrintBridge.scala
Labels: changelog:changed

#1126 correct doc for autocounter_csv_format
  docs/Advanced-Usage/Debugging-and-Profiling-on-FPGA/AutoCounter.rst
  docs/Advanced-Usage/Debugging-and-Profiling-on-FPGA/autocounter-csv-format.csv
Labels: changelog:fixed

#1144 ci: support running under forks of firesim
  .github/actions/initialize-manager/action.yml
  .github/actions/setup-workflow-monitor/action.yml
  .github/scripts/ci_variables.py
  .github/scripts/common.py
  .github/scripts/initialize-manager.py
  .github/scripts/initialize-repo.py
  .github/scripts/install-firesim-pem.py
  .github/scripts/local_flags.py
  .github/scripts/run-aws-configure.py
  .github/scripts/setup-manager-self-hosted.py
  .github/scripts/setup-workflow-monitor.py
  .github/scripts/workflow-monitor.py
  .github/workflows/firesim-run-tests.yml
Labels: changelog:changed
