Repository firesim/firesim, pull requests merged in 2022-04, with the labels that each got.

#1004 Add a Developer Section to docs.fires.im
  docs/Advanced-Usage/Debugging-and-Profiling-on-FPGA/Debugging-Hanging-Simulators.rst
  docs/Advanced-Usage/Debugging-and-Profiling-on-FPGA/Dromajo.rst
  docs/Advanced-Usage/Debugging-in-Software/RTL-Simulation.rst
  docs/Advanced-Usage/Generating-Different-Targets.rst
  docs/Developer-Docs/GoldenGate-and-Driver-Development.rst
  docs/Developer-Docs/Host-Platform-Debugging.rst
  docs/Golden-Gate/Bridge-Walkthrough.rst
  docs/index.rst
Labels: changelog:added

#1003 revert the change from #842 that makes launchrunfarm block on instances passing status checks
  deploy/awstools/awstools.py
  deploy/firesim
  deploy/runtools/firesim_topology_with_passes.py
  deploy/runtools/run_farm.py
Labels: Please Backport, changelog:fixed, ci:fpga-deploy

#1008 [Docs] Add a role :gh-file-ref: to simplify Github.com file references
  docs/Advanced-Usage/Generating-Different-Targets.rst
  docs/Developer-Docs/GoldenGate-and-Driver-Development.rst
  docs/conf.py
  docs/requirements.txt
Labels: changelog:omit

#1011 fireperf: Capture packet dump from switch
  target-design/switch/switch.cc
Labels: changelog:added, ci:fpga-deploy

#1018 post-merge CI needs to source env changes from machine-launch-script.sh
  .github/actions/machinelaunchscript/action.yml
  scripts/machine-launch-script.sh
Labels: changelog:omit

#1025 [ci] Run ScalaDoc builds on PRs to main and stable/backport branches
  .github/workflows/firesim-publish-scala-doc.yml
Labels: changelog:omit

#1010 `_` instead of `-`-based YAML files + API changes
  deploy/buildtools/buildafi.py
  deploy/buildtools/buildconfig.py
  deploy/buildtools/buildconfigfile.py
  deploy/buildtools/buildfarm.py
  deploy/runtools/runtime_config.py
  deploy/runtools/user_topology.py
  deploy/sample-backup-configs/sample_config_build.yaml
  deploy/sample-backup-configs/sample_config_build_farm.yaml
  deploy/sample-backup-configs/sample_config_build_recipes.yaml
  deploy/sample-backup-configs/sample_config_hwdb.yaml
  deploy/sample-backup-configs/sample_config_runtime.yaml
  deploy/tests/test_yaml_api.py
  deploy/workloads/bw-test-config.yaml
  deploy/workloads/ccbench-cache-sweep.yaml
  deploy/workloads/gapbs.yaml
  deploy/workloads/linux-poweroff-all-no-nic.yaml
  deploy/workloads/linux-poweroff-nic.yaml
  deploy/workloads/memcached-thread-imbalance-config.yaml
  deploy/workloads/ping-latency-config.yaml
  deploy/workloads/replace-agfi-used.sh
  deploy/workloads/run-bw-test.sh
  deploy/workloads/run-ping-latency.sh
  deploy/workloads/run-simperf-test-latency.sh
  deploy/workloads/run-simperf-test-scale-supernode.sh
  deploy/workloads/run-simperf-test-scale.sh
  deploy/workloads/simperf-test-latency-config.yaml
  deploy/workloads/simperf-test-scale-config.yaml
  deploy/workloads/simperf-test-scale-supernode-config.yaml
  deploy/workloads/spec17-intrate.yaml
  deploy/workloads/spec17-intspeed.yaml
Labels: changelog:omit, ci:fpga-deploy

#1024 [ci] Cleaner propagation of env after machine launch for containers
  .github/actions/buildsetup/action.yml
  .github/actions/machinelaunchscript/action.yml
  sim/midas/targetutils/src/main/scala/midas/annotations.scala
Labels: changelog:omit

#1032 ci: Fix git configuration in scaladoc publishing
  .github/actions/push-scaladoc-to-ghpages/action.yml
Labels: changelog:omit

#1035 Small CI cleanup
  .github/scripts/common.py
  .github/scripts/launch-manager-instance.py
Labels: changelog:omit

#1034 pin bison for current riscv-toolchain build from source
  scripts/machine-launch-script.sh
Labels: changelog:omit

#996 Collect Bridge Stream RTL Implementation under StreamEngine module
  deploy/sample-backup-configs/sample_config_hwdb.yaml
  sim/firesim-lib/src/main/cc/bridges/dromajo.cc
  sim/firesim-lib/src/main/cc/bridges/dromajo.h
  sim/firesim-lib/src/main/cc/bridges/simplenic.cc
  sim/firesim-lib/src/main/cc/bridges/simplenic.h
  sim/firesim-lib/src/main/cc/bridges/tracerv.cc
  sim/firesim-lib/src/main/cc/bridges/tracerv.h
  sim/firesim-lib/src/main/scala/bridges/DromajoBridge.scala
  sim/firesim-lib/src/main/scala/bridges/SimpleNICBridge.scala
  sim/firesim-lib/src/main/scala/bridges/TracerVBridge.scala
  sim/midas/src/main/cc/bridges/synthesized_prints.cc
  sim/midas/src/main/cc/bridges/synthesized_prints.h
  sim/midas/src/main/scala/midas/core/CPUManagedStreamEngine.scala
  sim/midas/src/main/scala/midas/core/FPGAManagedStreamEngine.scala
  sim/midas/src/main/scala/midas/core/FPGATop.scala
  sim/midas/src/main/scala/midas/core/StreamAllocator.scala
  sim/midas/src/main/scala/midas/core/StreamEngine.scala
  sim/midas/src/main/scala/midas/platform/F1Shim.scala
  sim/midas/src/main/scala/midas/widgets/DMATransport.scala
  sim/midas/src/main/scala/midas/widgets/Lib.scala
  sim/midas/src/main/scala/midas/widgets/PrintBridge.scala
  sim/midas/src/main/scala/midas/widgets/UsesBridgeStreams.scala
  sim/midas/src/main/scala/midas/widgets/Widget.scala
  sim/src/main/cc/firesim/firesim_top.cc
Labels: changelog:changed, ci:fpga-deploy

#1038 CI: Catch bad manager initialization in workflow control flow
  .github/workflows/firesim-run-tests.yml
Labels: changelog:omit

#1040 Fix CI FPGA sim timeout issue + Use Python3 formatting in `run_linux_poweroff` CI script
  .github/scripts/run-linux-poweroff.py
Labels: ci:fpga-deploy

#1037 awstools typing + small organization
  .github/scripts/requirements.txt
  deploy/awstools/awstools.py
Labels: changelog:changed

#1041 add bash-completion and install argcomplete global into it
  scripts/machine-launch-script.sh
Labels: changelog:fixed

#853 ("what-to-build") Modularize different run platforms (i.e. bitstream builds)
  deploy/awstools/awstools.py
  deploy/buildtools/bitbuilder.py
  deploy/buildtools/buildafi.py
  deploy/buildtools/buildconfig.py
  deploy/buildtools/buildconfigfile.py
  deploy/firesim
  deploy/sample-backup-configs/sample_config_hwdb.yaml
  deploy/ssh-setup.sh
  deploy/tests/test_firesim_top.py
  deploy/tests/test_yaml_api.py
  docs/Advanced-Usage/Manager/HELP_OUTPUT
  docs/Advanced-Usage/Manager/Manager-Tasks.rst
  docs/Building-a-FireSim-AFI.rst
  docs/Initial-Setup/Setting-up-your-Manager-Instance.rst
  regression/aws-ec2-tests/build-default-afis.sh
  scripts/machine-launch-script.sh
Labels: changelog:added, ci:fpga-deploy
