Repository firesim/firesim, pull requests merged in 2022-10, with the labels that each got.

#1242 Build PlatformShimElab from SimWrapperConfig
  sim/midas/src/main/scala/midas/passes/SimulationMapping.scala
  sim/midas/src/main/scala/midas/platform/PlatformShim.scala
  sim/midas/src/main/scala/midas/stage/RuntimeConfigGenerationPhase.scala
Labels: changelog:omit

#1246 Allow dromajo to be provided as a non-conda dependency
  sim/src/main/makefrag/firesim/Makefrag
Labels: changelog:omit

#1245 Bump to a conda-forge verilator 4.226 build that defaults to C++17
  conda-reqs.conda-lock.yml
  conda-reqs.yaml
Labels: changelog:omit

#1235 Add XDCAnnotation type hints, end-to-end test, empty arg list support
  sim/midas/src/main/scala/midas/passes/WriteXDCFile.scala
  sim/midas/targetutils/src/main/scala/midas/xdc/XDCAnnotation.scala
  sim/src/main/cc/midasexamples/CustomConstraints.h
  sim/src/main/cc/midasexamples/Driver.cc
  sim/src/main/scala/midasexamples/CustomConstraints.scala
  sim/src/test/scala/midasexamples/TutorialSuite.scala
Labels: changelog:fixed

#1243 Fix fasedtests with complex configs
  sim/midas/src/main/cc/unittest/Makefrag
  sim/src/main/makefrag/fasedtests/Makefrag
  sim/src/main/makefrag/midasexamples/Makefrag
Labels: changelog:omit

#1225 Materialized bridge FCCAs in BridgeExtraction
  sim/midas/src/main/scala/midas/passes/ExtractBridges.scala
  sim/midas/src/main/scala/midas/passes/fame/Annotations.scala
  sim/midas/src/main/scala/midas/widgets/Bridge.scala
  sim/midas/src/main/scala/midas/widgets/BridgeAnnotations.scala
  sim/midas/src/main/scala/midas/widgets/ChannelizedHostPort.scala
  sim/midas/src/main/scala/midas/widgets/ClockBridge.scala
  sim/midas/src/main/scala/midas/widgets/HostPort.scala
Labels: changelog:omit

#1244 Added a method to the shim for the generation of .vh files
  sim/midas/src/main/scala/midas/passes/SimulationMapping.scala
  sim/midas/src/main/scala/midas/platform/PlatformShim.scala
Labels: changelog:omit

#1249 TracerV: fix loop bounds in token processing
  sim/firesim-lib/src/main/cc/bridges/tracerv.cc
Labels: Please Backport, changelog:fixed, ci:fpga-deploy

#1253 Use headOptions instead of pattern matching in SimWrapper
  sim/midas/src/main/scala/midas/core/SimWrapper.scala
Labels: changelog:omit

#1251 Allow CreateParametersInstancePhase.getParameters to be reused
  sim/midas/src/main/scala/midas/stage/phases/CreateParametersInstancePhase.scala
Labels: changelog:omit

#1258 Properly ignore conda-env in ctagsignore
  .ctagsignore
Labels: changelog:omit

#1259 Update make examples in GoldenGate-and-Driver-Development.rst
  docs/Developer-Docs/GoldenGate-and-Driver-Development.rst
Labels: changelog:omit

#1267 Disable CI check for Local FPGAs
  .github/workflows/firesim-run-tests.yml
Labels: bug

#1272 add back InfoStreamLogger on driver build run call to show live build status
  deploy/runtools/runtime_config.py
Labels: changelog:fixed, ci:fpga-deploy

#1265 Bump CI to Ubuntu 20.04 + new checkout action
  .github/workflows/firesim-cleanup.yml
  .github/workflows/firesim-publish-scala-doc.yml
  .github/workflows/firesim-run-tests.yml
Labels: ci:fpga-deploy

#1274 Put instPath before label in AutoCounter output
  sim/midas/src/main/scala/midas/passes/AutoCounterTransform.scala
  sim/src/main/scala/midasexamples/AutoCounterValidator.scala
Labels: changelog:changed

#1264 Match field order in channel info
  sim/midas/src/main/scala/midas/widgets/HostPort.scala
Labels: changelog:omit

#1280 fix vcs metasims
  deploy/runtools/runtime_config.py
Labels: changelog:fixed, ci:fpga-deploy

#1257 Localize Java temp directory + Revert to using `sbt-launch.jar`
  sim/.java_tmp/.gitignore
  sim/Makefile
Labels: changelog:omit, ci:fpga-deploy

#1270 Vitis: support different bitstream build strategies
  platforms/vitis/cl_firesim/.gitignore
  platforms/vitis/cl_firesim/Makefile
  platforms/vitis/cl_firesim/build-bitstream.cfg
  platforms/vitis/cl_firesim/build-strategies/strategy_AREA.cfg
  platforms/vitis/cl_firesim/build-strategies/strategy_TIMING.cfg
Labels: changelog:added

#1285 build setup: make env.sh sourcable in contexts without conda functions
  .github/actions/buildsetup/action.yml
  build-setup-nolog.sh
Labels: changelog:fixed

#1262 Adding support for Azure CI
  .github/CI_README.md
  .github/actions/change-workflow-instance-states/action.yml
  .github/actions/setup-workflow-monitor/action.yml
  .github/scripts/change-workflow-instance-states.py
  .github/scripts/ci_variables.py
  .github/scripts/common.py
  .github/scripts/cull-old-ci-instances.py
  .github/scripts/initialize-repo.py
  .github/scripts/install-firesim-pem.py
  .github/scripts/launch-azure-vm.py
  .github/scripts/launch-manager-instance.py
  .github/scripts/platform_lib.py
  .github/scripts/requirements.txt
  .github/scripts/run-managerinit.py
  .github/scripts/run-sbt-command.py
  .github/scripts/run-scala-test.py
  .github/scripts/setup-manager-self-hosted.py
  .github/scripts/setup-workflow-monitor.py
  .github/scripts/workflow-monitor.py
  .github/workflows/firesim-cleanup.yml
  .github/workflows/firesim-run-tests.yml
  scripts/machine-launch-script.sh
Labels: changelog:omit

#1281 vitis: Support frequency settings provided at bitstream build
  .github/actions/build-scala-doc/action.yml
  .github/actions/buildsetup/action.yml
  .github/actions/repo-setup/action.yml
  deploy/bit-builder-recipes/vitis.yaml
  deploy/buildtools/bitbuilder.py
  deploy/buildtools/buildconfig.py
  deploy/buildtools/buildconfigfile.py
  deploy/sample-backup-configs/sample_config_build_recipes.yaml
  docs/Advanced-Usage/Debugging-and-Profiling-on-FPGA/Printf-Synthesis.rst
  docs/Advanced-Usage/Generating-Different-Targets.rst
  docs/Advanced-Usage/Manager/Manager-Configuration-Files.rst
  docs/External-Tutorial-Setup.rst
  docs/Running-Simulations-Tutorial/Running-a-Cluster-Simulation.rst
  docs/Running-Simulations-Tutorial/Running-a-Single-Node-Simulation.rst
  platforms/f1/build-bitstream.sh
  platforms/vitis/build-bitstream.sh
  platforms/vitis/cl_firesim/Makefile
  platforms/vitis/cl_firesim/scripts/gen_xo.tcl
  platforms/vitis/cl_firesim/scripts/package_kernel.tcl
  sim/midas/src/main/scala/midas/Config.scala
  sim/midas/src/main/scala/midas/platform/VitisShim.scala
  sim/midas/src/main/scala/midas/platform/xilinx/Clocking.scala
  sim/src/main/scala/midasexamples/Config.scala
Labels: changelog:added
