Repository firesim/firesim, pull requests merged in 2022-12, with the labels that each got.

#1317 Fixed invalid memory access of MMIO port addresses
  sim/firesim-lib/src/main/cc/bridges/uart.h
Labels: changelog:omit

#1316 CI Rework: More Aggressive Culling Of FPGA Resources, Slack/PR Notifications
  .github/scripts/ci_variables.py
  .github/scripts/common.py
  .github/scripts/cull-old-ci-instances.py
  .github/scripts/cull-old-ci-runners.py
  .github/scripts/github_common.py
  .github/scripts/initialize-repo.py
  .github/scripts/install-firesim-pem.py
  .github/scripts/launch-azure-vm.py
  .github/scripts/launch-manager-instance.py
  .github/scripts/platform_lib.py
  .github/scripts/run-aws-configure.py
  .github/scripts/run-linux-poweroff-externally-provisioned.py
  .github/scripts/run-linux-poweroff-vitis.py
  .github/scripts/run-linux-poweroff.py
  .github/scripts/run-managerinit.py
  .github/scripts/setup-manager-self-hosted.py
  .github/scripts/setup-workflow-monitor.py
  .github/scripts/workflow-monitor.py
  .github/workflows/firesim-cleanup.yml
  .github/workflows/firesim-run-tests.yml
  scripts/run-py-typecheck.sh
Labels: ci:fpga-deploy

#1326 Added UART bridge test
  .github/workflows/firesim-run-tests.yml
  docs/Advanced-Usage/Generating-Different-Targets.rst
  sim/firesim-lib/src/main/cc/bridges/uart.cc
  sim/firesim-lib/src/main/cc/bridges/uart.h
  sim/src/main/cc/bridges/UARTModule.cc
  sim/src/main/makefrag/bridges/Makefrag
  sim/src/main/scala/bridges/Config.scala
  sim/src/main/scala/bridges/UARTModule.scala
  sim/src/test/scala/bridges/BridgeSuite.scala
Labels: changelog:omit, ci:fpga-deploy

#1330 Added SimpleRocketF1Tests
  sim/src/test/scala/firesim/FireSimTestSuite.scala
Labels: changelog:omit

#1322 Move termination to Run Farm `Inst` + `monitor_jobs` small rework
  deploy/runtools/firesim_topology_with_passes.py
  deploy/runtools/run_farm.py
  deploy/runtools/run_farm_deploy_managers.py
  deploy/workloads/linux-poweroff-all-no-nic.yaml
  deploy/workloads/linux-poweroff-nic.yaml
Labels: ci:fpga-deploy

#1324 Add an Assert-mode for TerminationBridge; expand testing
  sim/midas/src/main/cc/bridges/termination.cc
  sim/midas/src/main/cc/bridges/termination.h
  sim/midas/src/main/cc/constructor.h
  sim/midas/src/main/scala/midas/widgets/TerminationBridge.scala
  sim/midas/targetutils/src/main/scala/midas/InstrumentationPredication.scala
  sim/src/main/cc/midasexamples/TestTerminationModuleAssert.cc
  sim/src/main/scala/midasexamples/Termination.scala
  sim/src/test/scala/midasexamples/TutorialSuite.scala
Labels: changelog:added

#1328 Introduced an interface to capture the user-defined logic of a simuation
  sim/midas/src/main/cc/Makefile
  sim/midas/src/main/cc/bridges/termination.h
  sim/midas/src/main/cc/emul/context.cc
  sim/midas/src/main/cc/emul/context.h
  sim/midas/src/main/cc/emul/mmio.h
  sim/midas/src/main/cc/emul/vcs-harness.cc
  sim/midas/src/main/cc/emul/vcs_main.h
  sim/midas/src/main/cc/emul/verilator-harness.cc
  sim/midas/src/main/cc/simif.cc
  sim/midas/src/main/cc/simif.h
  sim/midas/src/main/cc/simif_emul.cc
  sim/midas/src/main/cc/simif_emul.h
  sim/midas/src/main/cc/simif_emul_vcs.cc
  sim/midas/src/main/cc/simif_emul_vcs.h
  sim/midas/src/main/cc/simif_emul_verilator.cc
  sim/midas/src/main/cc/simif_emul_verilator.h
  sim/midas/src/main/cc/simif_f1.cc
  sim/midas/src/main/cc/simif_f1.h
  sim/midas/src/main/cc/simif_vitis.cc
  sim/midas/src/main/cc/simif_vitis.h
  sim/src/main/cc/bridges/UARTModule.cc
  sim/src/main/cc/fasedtests/fasedtests_top.cc
  sim/src/main/cc/fasedtests/fasedtests_top.h
  sim/src/main/cc/firesim/firesim_f1.cc
  sim/src/main/cc/firesim/firesim_top.cc
  sim/src/main/cc/firesim/firesim_top.h
  sim/src/main/cc/firesim/firesim_vitis.cc
  sim/src/main/cc/midasexamples/TestAssertModule.cc
  sim/src/main/cc/midasexamples/TestHarness.h
  sim/src/main/cc/midasexamples/TestMultiSRAM.cc
  sim/src/main/cc/midasexamples/TestPlusArgsModule.cc
  sim/src/main/cc/midasexamples/TestTerminationModuleAssert.cc
  sim/src/main/cc/midasexamples/simif_peek_poke.cc
  sim/src/main/makefrag/firesim/Makefrag
Labels: changelog:omit

#1334 Fixed firesim.bridges CI tests
  .github/workflows/firesim-run-tests.yml
  sim/src/main/makefrag/bridges/Makefrag
Labels: changelog:omit

#1338 Provided tests with their own random number generator
  sim/src/main/cc/midasexamples/ShiftRegisterTest.h
  sim/src/main/cc/midasexamples/TestEnableShiftRegister.cc
  sim/src/main/cc/midasexamples/TestHarness.h
  sim/src/main/cc/midasexamples/TestParity.cc
  sim/src/main/cc/midasexamples/TestResetShiftRegister.cc
  sim/src/main/cc/midasexamples/TestStack.cc
  sim/src/main/cc/midasexamples/TestTerminationModule.cc
  sim/src/main/cc/midasexamples/TestWireInterconnect.cc
Labels: changelog:omit

#1331 Moved MMIO struct type definitions to headers
  sim/firesim-lib/src/main/cc/bridges/blockdev.cc
  sim/firesim-lib/src/main/cc/bridges/blockdev.h
  sim/firesim-lib/src/main/cc/bridges/dromajo.cc
  sim/firesim-lib/src/main/cc/bridges/dromajo.h
  sim/firesim-lib/src/main/cc/bridges/groundtest.cc
  sim/firesim-lib/src/main/cc/bridges/groundtest.h
  sim/firesim-lib/src/main/cc/bridges/serial.cc
  sim/firesim-lib/src/main/cc/bridges/serial.h
  sim/firesim-lib/src/main/cc/bridges/simplenic.cc
  sim/firesim-lib/src/main/cc/bridges/simplenic.h
  sim/firesim-lib/src/main/cc/bridges/tracerv.cc
  sim/firesim-lib/src/main/cc/bridges/tracerv.h
  sim/firesim-lib/src/main/cc/bridges/uart.cc
  sim/firesim-lib/src/main/cc/bridges/uart.h
  sim/midas/src/main/cc/bridges/autocounter.cc
  sim/midas/src/main/cc/bridges/autocounter.h
  sim/midas/src/main/cc/bridges/fased_memory_timing_model.h
  sim/midas/src/main/cc/bridges/fpga_model.h
  sim/midas/src/main/cc/bridges/plusargs.cc
  sim/midas/src/main/cc/bridges/plusargs.h
  sim/midas/src/main/cc/bridges/reset_pulse.cc
  sim/midas/src/main/cc/bridges/reset_pulse.h
  sim/midas/src/main/cc/bridges/synthesized_assertions.cc
  sim/midas/src/main/cc/bridges/synthesized_assertions.h
  sim/midas/src/main/cc/bridges/synthesized_prints.cc
  sim/midas/src/main/cc/bridges/synthesized_prints.h
  sim/midas/src/main/cc/bridges/termination.cc
  sim/midas/src/main/cc/bridges/termination.h
  sim/midas/src/main/cc/constructor.h
  sim/midas/src/main/cc/simif.h
  sim/midas/src/main/scala/midas/core/FPGATop.scala
  sim/midas/src/main/scala/midas/models/dram/FASEDMemoryTimingModel.scala
  sim/midas/src/main/scala/midas/platform/PlatformShim.scala
  sim/midas/src/main/scala/midas/widgets/Lib.scala
  sim/midas/src/main/scala/midas/widgets/LoadMem.scala
  sim/midas/src/main/scala/midas/widgets/PeekPokeIO.scala
  sim/midas/src/main/scala/midas/widgets/PlusArgsBridge.scala
  sim/midas/src/main/scala/midas/widgets/Widget.scala
  sim/src/main/cc/fasedtests/fasedtests_top.cc
  sim/src/main/cc/fasedtests/fasedtests_top.h
  sim/src/main/cc/midasexamples/TestHarness.h
  sim/src/main/cc/midasexamples/simif_peek_poke.h
  sim/src/main/makefrag/midasexamples/Makefrag
Labels: changelog:added, ci:fpga-deploy

#1335 Added a test for the BlockDevBridge
  sim/src/main/cc/bridges/BlockDevModule.cc
  sim/src/main/scala/bridges/BlockDevModule.scala
  sim/src/main/scala/bridges/Config.scala
  sim/src/test/scala/bridges/BridgeSuite.scala
Labels: changelog:omit

#1339 Moved widget logic to individual classes
  sim/firesim-lib/src/main/cc/bridges/serial.cc
  sim/midas/src/main/cc/bridges/clock.cc
  sim/midas/src/main/cc/bridges/clock.h
  sim/midas/src/main/cc/bridges/loadmem.cc
  sim/midas/src/main/cc/bridges/loadmem.h
  sim/midas/src/main/cc/bridges/master.cc
  sim/midas/src/main/cc/bridges/master.h
  sim/midas/src/main/cc/simif.cc
  sim/midas/src/main/cc/simif.h
  sim/midas/src/main/cc/simif_emul.cc
Labels: changelog:omit

#1337 [SimWrapper] Remove unused SimReadyValidRecord; NFC
  sim/midas/src/main/scala/midas/core/SimWrapper.scala
Labels: changelog:removed

#1343 Fix documentation on Vitis deploy manager
  docs/Advanced-Usage/Vitis.rst
Labels: changelog:omit

#1332 Switch VCS simulation over to DPI
  sim/midas/src/main/cc/Makefile
  sim/midas/src/main/cc/emul/mm.cc
  sim/midas/src/main/cc/emul/mm.h
  sim/midas/src/main/cc/emul/mmio.cc
  sim/midas/src/main/cc/emul/mmio.h
  sim/midas/src/main/cc/emul/vcs-harness.cc
  sim/midas/src/main/cc/rtlsim/Makefrag-vcs
  sim/midas/src/main/cc/simif_emul_verilator.cc
  sim/midas/src/main/scala/midas/core/FPGATop.scala
  sim/midas/src/main/verilog/vcs_top.sv
  sim/midas/src/main/verilog/vcs_top.v
Labels: changelog:omit, ci:fpga-deploy

#1336 Introduced a uniform harness over bridge tests
  sim/firesim-lib/src/main/cc/bridges/uart.cc
  sim/firesim-lib/src/main/cc/bridges/uart.h
  sim/midas/src/main/cc/constructor.h
  sim/src/main/cc/bridges/BlockDevModule.cc
  sim/src/main/cc/bridges/BridgeHarness.cc
  sim/src/main/cc/bridges/BridgeHarness.h
  sim/src/main/cc/bridges/UARTModule.cc
  sim/src/main/makefrag/bridges/Makefrag
  sim/src/test/scala/bridges/BridgeSuite.scala
Labels: changelog:omit, ci:fpga-deploy
