Repository firesim/firesim, pull requests merged in 2022-08, with the labels that each got.

#1149 ci: set MANAGER_FIRESIM_LOCATION in all workflows
  .github/workflows/firesim-cull-instances.yml
  .github/workflows/firesim-publish-scala-doc.yml
Labels: changelog:omit

#1151 Annotate Printf statements instead of intercepting parameters.
  docs/Advanced-Usage/Debugging-and-Profiling-on-FPGA/Printf-Synthesis.rst
  sim/midas/src/main/scala/midas/passes/AutoCounterTransform.scala
  sim/midas/src/main/scala/midas/passes/PrintSynthesis.scala
  sim/midas/targetutils/src/main/scala/midas/annotations.scala
  sim/src/main/scala/midasexamples/GlobalResetConditionTests.scala
  sim/src/main/scala/midasexamples/PrintfModule.scala
  sim/src/main/scala/midasexamples/TriggerPredicatedPrintf.scala
  sim/src/test/scala/midasexamples/TutorialSuite.scala
Labels: changelog:fixed

#1155 add tests for downloadURI
  deploy/runtools/run_farm_deploy_managers.py
  deploy/tests/conftest.py
  deploy/tests/fsspec_test_json.json
  deploy/tests/test_utils.py
  deploy/util/io.py
Labels: changelog:omit

#1104 Make bug report system info copy pastable
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: changelog:changed

#1135 CI Runner Cleanup
  .github/scripts/ci_variables.py
  .github/scripts/common.py
  .github/scripts/cull-old-ci-instances.py
  .github/scripts/cull-old-ci-runners.py
  .github/scripts/initialize-repo.py
  .github/scripts/setup-manager-self-hosted.py
  .github/workflows/firesim-cleanup.yml
Labels: changelog:omit

#1140 add xclbin URI support
  .github/scripts/requirements.txt
  deploy/runtools/run_farm_deploy_managers.py
  deploy/runtools/runtime_config.py
  deploy/tests/conftest.py
  deploy/tests/fsspec_test_json.json
  deploy/tests/test_utils.py
  deploy/util/io.py
  docs/Advanced-Usage/Manager/Manager-Configuration-Files.rst
  scripts/machine-launch-script.sh
Labels: changelog:added

#1168 Fix switch build under clang-format header order
  target-design/switch/baseport.h
  target-design/switch/flit.h
  target-design/switch/shmemport.h
  target-design/switch/socketport.h
  target-design/switch/sshport.h
Labels: changelog:omit, ci:fpga-deploy

#1173 Revert "add xclbin URI support (#1140)"
  .github/scripts/requirements.txt
  deploy/runtools/run_farm_deploy_managers.py
  deploy/runtools/runtime_config.py
  deploy/tests/conftest.py
  deploy/tests/fsspec_test_json.json
  deploy/tests/test_utils.py
  deploy/util/io.py
  docs/Advanced-Usage/Manager/Manager-Configuration-Files.rst
  scripts/machine-launch-script.sh
Labels: changelog:omit, ci:fpga-deploy

#1163 obey umask and default group in results-workload
  deploy/runtools/firesim_topology_elements.py
Labels: changelog:changed, ci:fpga-deploy

#1156 Bump to Verilator 4.224
  scripts/machine-launch-script.sh
Labels: changelog:changed

#1177 Fix various VCS metasimulation breakages
  sim/midas/src/main/cc/Makefile
  sim/midas/src/main/cc/emul/mmio.cc
  sim/midas/src/main/cc/emul/mmio.h
  sim/midas/src/main/cc/emul/vcs-harness.cc
  sim/midas/src/main/cc/emul/verilator-harness.cc
  sim/midas/src/main/cc/simif_emul.cc
  sim/midas/src/main/cc/simif_emul.h
  sim/target-agnostic.mk
Labels: changelog:fixed, ci:fpga-deploy

#1185 ci: remove termination bridge test until it is fixed
  sim/src/test/scala/midasexamples/TutorialSuite.scala
Labels: changelog:omit

#1186 Resolve some common spelling mistakes
  CHANGELOG.md
  deploy/runtools/utils.py
  platforms/vitis/cl_firesim/Makefile
  sim/midas/README.md
  sim/midas/src/main/cc/rtlsim/ml-verilator-conf.vlt
  sim/midas/src/main/scala/midas/passes/HoistStopAndPrintfEnables.scala
  sim/midas/src/main/scala/midas/stage/GoldenGateCompilerPhase.scala
  sim/midas/src/main/scala/midas/widgets/HostPort.scala
Labels: changelog:omit

#1176 Backports go to stable branch, which should generally point to the la…
  .mergify.yml
Labels: changelog:changed
