Repository firesim/firesim, pull requests merged in 2023-03, with the labels that each got.

#1443 pickup fab-classic#77 by bumping to 1.19.2
  .github/scripts/requirements.txt
  conda-reqs.conda-lock.yml
  conda-reqs.yaml
Labels: changelog:changed

#1446 Bump SBT to 1.8.2
  sim/project/build.properties
Labels: ci:fpga-deploy

#1442 Removed test_harness_bridge and simplified harnesses
  sim/midas/src/main/cc/core/systematic_scheduler.cc
  sim/midas/src/main/cc/core/systematic_scheduler.h
  sim/src/main/cc/fasedtests/fasedtests_top.cc
  sim/src/main/cc/fasedtests/test_harness_bridge.cc
  sim/src/main/cc/fasedtests/test_harness_bridge.h
  sim/src/main/cc/firesim/firesim_top.cc
Labels: changelog:omit

#1432 Add URI support to tarball path and xclbin path
  .github/scripts/requirements.txt
  .github/scripts/run-linux-poweroff-vitis.py
  .github/scripts/run-parallel-verilator-metasims.py
  .github/workflows/firesim-run-tests.yml
  conda-reqs.conda-lock.yml
  conda-reqs.yaml
  deploy/runtools/firesim_topology_elements.py
  deploy/runtools/firesim_topology_with_passes.py
  deploy/runtools/run_farm_deploy_managers.py
  deploy/runtools/runtime_config.py
  deploy/tests/fsspec_test_json.json
  deploy/tests/test_utils.py
  deploy/util/io.py
  deploy/workloads/ci/hello-world-localhost-vcs-metasim.yaml
  deploy/workloads/ci/vitis/config_hwdb.yaml
  docs/Advanced-Usage/Manager/Manager-Configuration-Files.rst
  docs/Advanced-Usage/Manager/Manager-URI-Paths.rst
  docs/Advanced-Usage/Manager/index.rst
  scripts/machine-launch-script.sh
Labels: changelog:added, ci:fpga-deploy

#1449 Add ci:persist-prior-workflows tag to allow prior workflow to run until completion
  .github/CI_README.md
  .github/workflows/firesim-run-tests.yml
Labels: changelog:added, ci:persist-prior-workflows

#1451 Unpin most conda reqs now that we have a lockfile
  build-setup-nolog.sh
  conda-reqs/conda-reqs.conda-lock.yml
  conda-reqs/firesim.yaml
  deploy/runtools/firesim_topology_elements.py
  deploy/util/streamlogger.py
Labels: ci:fpga-deploy

#1454 Add uartlog checking to Linux boots in CI
  .github/scripts/run-linux-poweroff-externally-provisioned.py
  .github/scripts/run-linux-poweroff-vitis.py
  .github/scripts/run-linux-poweroff.py
Labels: ci:fpga-deploy

#1463 Revert to UInt64 for offsetConst in SerialBridge
  sim/firesim-lib/src/main/scala/bridges/SerialBridge.scala
Labels: bug

#1460 Support AL2 manager instances
  .github/scripts/setup-manager-self-hosted.py
  deploy/awstools/awstools.py
  deploy/runtools/run_farm.py
  deploy/runtools/run_farm_deploy_managers.py
  docs/Initial-Setup/Setting-up-your-Manager-Instance.rst
  regression/aws-ec2-tests/launch-setup-manager-instance.sh
  scripts/machine-launch-script.sh
Labels: ci:fpga-deploy

#1383 Expand TracerV to support more than 7 IPC
  sim/firesim-lib/src/main/cc/bridges/tracerv.cc
  sim/firesim-lib/src/main/cc/bridges/tracerv.h
  sim/firesim-lib/src/main/scala/bridges/TracerVBridge.scala
  sim/src/main/cc/bridges/TracerVModule.cc
  sim/src/main/scala/bridges/TracerVModule.scala
  sim/src/test/scala/bridges/TracerVSuite.scala
Labels: changelog:added

#1467 Fix uartlog checking in CI for Linux boot
  .github/scripts/run-linux-poweroff-externally-provisioned.py
  .github/scripts/run-linux-poweroff-vitis.py
  .github/scripts/run-linux-poweroff.py
Labels: ci:fpga-deploy

#1478 Fix conda lockfile docs / make lockfile generation easier
  build-setup-nolog.sh
  docs/Developer-Docs/Managing-Conda-Lock-File.rst
  scripts/generate-conda-lockfile.sh
Labels: changelog:omit

#1488 Update Makefile to be non-parallel
  sim/Makefile
Labels: ci:fpga-deploy
