Repository firesim/firesim, pull requests merged in 2023-02, with the labels that each got.

#1368 [library] Introduced a unique main to the simulation.
  sim/firesim-lib/src/main/cc/bridges/serial.cc
  sim/make/cpp-lint.mk
  sim/midas/src/main/cc/bridges/peek_poke.h
  sim/midas/src/main/cc/core/constructor.h
  sim/midas/src/main/cc/core/main.cc
  sim/midas/src/main/cc/core/simif.cc
  sim/midas/src/main/cc/core/simif.h
  sim/midas/src/main/cc/core/widget_registry.cc
  sim/midas/src/main/cc/core/widget_registry.h
  sim/midas/src/main/cc/emul/simif_emul.cc
  sim/midas/src/main/cc/emul/simif_emul.h
  sim/midas/src/main/cc/simif_emul_vcs.cc
  sim/midas/src/main/cc/simif_emul_verilator.cc
  sim/midas/src/main/cc/simif_f1.cc
  sim/midas/src/main/cc/simif_f1_xsim.cc
  sim/midas/src/main/cc/simif_vitis.cc
  sim/src/main/cc/firesim/firesim_top.cc
Labels: changelog:changed

#1416 Passed memory region offsets to genHeader
  sim/firesim-lib/src/main/scala/bridges/BlockDevBridge.scala
  sim/firesim-lib/src/main/scala/bridges/DromajoBridge.scala
  sim/firesim-lib/src/main/scala/bridges/SerialBridge.scala
  sim/firesim-lib/src/main/scala/bridges/TracerVBridge.scala
  sim/midas/src/main/scala/midas/core/CPUManagedStreamEngine.scala
  sim/midas/src/main/scala/midas/core/FPGAManagedStreamEngine.scala
  sim/midas/src/main/scala/midas/core/FPGATop.scala
  sim/midas/src/main/scala/midas/models/dram/FASEDMemoryTimingModel.scala
  sim/midas/src/main/scala/midas/widgets/AssertBridge.scala
  sim/midas/src/main/scala/midas/widgets/AutoCounterBridge.scala
  sim/midas/src/main/scala/midas/widgets/LoadMem.scala
  sim/midas/src/main/scala/midas/widgets/PeekPokeIO.scala
  sim/midas/src/main/scala/midas/widgets/PlusArgsBridge.scala
  sim/midas/src/main/scala/midas/widgets/PrintBridge.scala
  sim/midas/src/main/scala/midas/widgets/ResetPulseBridge.scala
  sim/midas/src/main/scala/midas/widgets/TerminationBridge.scala
  sim/midas/src/main/scala/midas/widgets/UsesHostDRAM.scala
  sim/midas/src/main/scala/midas/widgets/Widget.scala
Labels: changelog:omit

#1423 Re-enabled timeout detection for harnesses
  sim/src/main/cc/fasedtests/fasedtests_top.cc
  sim/src/main/cc/firesim/firesim_top.cc
Labels: changelog:omit

#1424 Removed auxiliary functions from simif_t
  sim/firesim-lib/src/main/cc/bridges/serial.cc
  sim/midas/src/main/cc/bridges/clock.cc
  sim/midas/src/main/cc/bridges/heartbeat.cc
  sim/midas/src/main/cc/bridges/heartbeat.h
  sim/midas/src/main/cc/bridges/master.cc
  sim/midas/src/main/cc/core/main.cc
  sim/midas/src/main/cc/core/simif.cc
  sim/midas/src/main/cc/core/simif.h
  sim/midas/src/main/cc/core/simulation.cc
  sim/midas/src/main/cc/core/simulation.h
  sim/midas/src/main/cc/emul/simif_emul.cc
  sim/midas/src/main/cc/emul/simif_emul.h
  sim/midas/src/main/cc/simif_f1.cc
  sim/midas/src/main/cc/simif_f1_xsim.cc
  sim/midas/src/main/cc/simif_vitis.cc
  sim/src/main/cc/bridges/BridgeHarness.cc
  sim/src/main/cc/bridges/BridgeHarness.h
  sim/src/main/cc/fasedtests/fasedtests_top.cc
  sim/src/main/cc/fasedtests/test_harness_bridge.cc
  sim/src/main/cc/fasedtests/test_harness_bridge.h
  sim/src/main/cc/firesim/firesim_top.cc
  sim/src/main/cc/midasexamples/TestHarness.cc
  sim/src/main/cc/midasexamples/TestHarness.h
  sim/src/main/cc/midasexamples/TestMultiSRAM.cc
  sim/src/main/cc/midasexamples/TestPlusArgsModule.cc
Labels: changelog:changed

#1429 Enabled scalafmt on more sources
  sim/.scalafmt.conf
  sim/midas/src/main/scala/midas/core/FPGATop.scala
  sim/midas/src/main/scala/midas/platform/F1Shim.scala
  sim/midas/src/main/scala/midas/platform/PlatformShim.scala
  sim/midas/src/main/scala/midas/widgets/Lib.scala
  sim/midas/src/main/scala/midas/widgets/Widget.scala
Labels: changelog:omit

#1426 Test for existing TracerV bridge including trigger modes
  sim/firesim-lib/src/main/cc/bridges/tracerv.cc
  sim/firesim-lib/src/main/cc/bridges/tracerv.h
  sim/firesim-lib/src/main/scala/bridges/TracerVBridge.scala
  sim/make/cpp-lint.mk
  sim/src/main/cc/bridges/BridgeHarness.cc
  sim/src/main/cc/bridges/TracerVModule.cc
  sim/src/main/makefrag/bridges/driver.mk
  sim/src/main/scala/bridges/TracerVModule.scala
  sim/src/test/scala/bridges/BridgeSuite.scala
  sim/src/test/scala/bridges/TracerVSuite.scala
Labels: changelog:added

#1430 Do not materialize a stream engine if no streams are used
  sim/midas/src/main/scala/midas/core/FPGATop.scala
  sim/midas/src/main/scala/midas/platform/F1Shim.scala
Labels: changelog:changed

#1433 Added a test for memory accesses and LoadMemWidget
  sim/midas/src/main/cc/bridges/loadmem.cc
  sim/midas/src/main/cc/core/simulation.cc
  sim/src/main/cc/midasexamples/TestLoadMemModule.cc
  sim/src/main/scala/midasexamples/LoadMemModule.scala
  sim/src/test/scala/midasexamples/MemorySuite.scala
Labels: changelog:added

#1435 Introduced a full verilator/vcs/debug matrix
  sim/.scalafmt.conf
  sim/firesim-lib/src/test/scala/TestSuiteCommon.scala
  sim/make/scala-build.mk
  sim/src/main/scala/midasexamples/TriggerPredicatedPrintf.scala
  sim/src/test/scala/bridges/BridgeSuite.scala
  sim/src/test/scala/bridges/TracerVSuite.scala
  sim/src/test/scala/fasedtests/FASEDTestSuite.scala
  sim/src/test/scala/firesim/FireSimTestSuite.scala
  sim/src/test/scala/midasexamples/AssertSuite.scala
  sim/src/test/scala/midasexamples/AutoCounterSuite.scala
  sim/src/test/scala/midasexamples/ChiselExampleDesigns.scala
  sim/src/test/scala/midasexamples/FMRSuite.scala
  sim/src/test/scala/midasexamples/GoldenGateMiscSuite.scala
  sim/src/test/scala/midasexamples/MemorySuite.scala
  sim/src/test/scala/midasexamples/PlusArgSuite.scala
  sim/src/test/scala/midasexamples/PrintfSuite.scala
  sim/src/test/scala/midasexamples/ResetPulseSuite.scala
  sim/src/test/scala/midasexamples/TutorialSuite.scala
Labels: changelog:added, changelog:changed

#1434 Add option to the F1 driver to load an AGFI
  sim/midas/src/main/cc/simif_f1.cc
Labels: changelog:added

#1431 Do not materialize memory connections if the target does not use them
  sim/midas/src/main/cc/core/simulation.cc
  sim/midas/src/main/cc/core/widget_registry.h
  sim/midas/src/main/cc/emul/simif_emul.cc
  sim/midas/src/main/scala/midas/core/FPGATop.scala
  sim/midas/src/main/scala/midas/platform/F1Shim.scala
  sim/midas/src/main/scala/midas/platform/VitisShim.scala
  sim/midas/src/main/scala/midas/platform/xilinx/AXI4Crossing.scala
  sim/src/test/scala/midasexamples/MemorySuite.scala
  sim/src/test/scala/midasexamples/TutorialSuite.scala
Labels: changelog:changed

#1437 Fix wiring of unused ports
  sim/midas/src/main/scala/midas/platform/F1Shim.scala
  sim/midas/src/main/scala/midas/platform/xilinx/AXI4Crossing.scala
Labels: changelog:omit

#1438 VCS post-synthesis RTL simulators
  sim/Makefile
  sim/make/goldengate.mk
  sim/make/post-synth.mk
  sim/make/vcs.mk
  sim/midas/src/main/cc/Makefile
  sim/midas/src/main/cc/rtlsim/Makefrag-vcs
  sim/midas/src/main/verilog/top.sv
  sim/scripts/synth_fpga.tcl
Labels: changelog:added

#1427 Update doc of always_expand_run_farm for rename
  docs/Advanced-Usage/Manager/Manager-Configuration-Files.rst
Labels: changelog:changed

#1444 Fix replace-rtl ordering problem
  sim/make/fpga.mk
Labels: changelog:fixed

#1441 Move bridge init/finish handling into the simulation base
  sim/midas/src/main/cc/core/simulation.cc
  sim/midas/src/main/cc/core/simulation.h
  sim/src/main/cc/bridges/BridgeHarness.cc
  sim/src/main/cc/bridges/BridgeHarness.h
  sim/src/main/cc/bridges/TracerVModule.cc
  sim/src/main/cc/fasedtests/fasedtests_top.cc
  sim/src/main/cc/fasedtests/test_harness_bridge.cc
  sim/src/main/cc/fasedtests/test_harness_bridge.h
  sim/src/main/cc/firesim/firesim_top.cc
  sim/src/main/cc/midasexamples/AssertTest.h
  sim/src/main/cc/midasexamples/AutoCounterTest.h
  sim/src/main/cc/midasexamples/PrintfTest.h
  sim/src/main/cc/midasexamples/TestAssertGlobalResetCondition.cc
  sim/src/main/cc/midasexamples/TestAssertModule.cc
  sim/src/main/cc/midasexamples/TestAssertTorture.cc
  sim/src/main/cc/midasexamples/TestHarness.h
  sim/src/main/cc/midasexamples/TestMulticlockAssertModule.cc
  sim/src/main/cc/midasexamples/TestMulticlockAutoCounterModule.cc
  sim/src/main/cc/midasexamples/TestMulticlockPrintfModule.cc
  sim/src/main/cc/midasexamples/TestPlusArgsModule.cc
  sim/src/main/cc/midasexamples/TestPrintfGlobalResetCondition.cc
  sim/src/main/cc/midasexamples/TestResetPulseBridgeTest.cc
  sim/src/main/cc/midasexamples/TestTriggerWiringModule.cc
Labels: changelog:omit
