Repository firesim/firesim, pull requests merged in 2023-01, with the labels that each got.

#1357 manager: update paramiko date threshold
  deploy/firesim
Labels: changelog:omit

#1360 Fixed GCC/Clang compilation issues
  sim/midas/src/main/cc/simif_emul.cc
Labels: changelog:omit

#1364 Improve the names of synchronisation primitives in `simif_emul`
  sim/midas/src/main/cc/simif_emul.cc
  sim/midas/src/main/cc/simif_emul.h
Labels: changelog:omit

#1358 Replace AXI4 configuration with structures
  sim/midas/src/main/cc/bridges/cpu_managed_stream.cc
  sim/midas/src/main/cc/bridges/cpu_managed_stream.h
  sim/midas/src/main/cc/bridges/loadmem.cc
  sim/midas/src/main/cc/bridges/loadmem.h
  sim/midas/src/main/cc/config.h
  sim/midas/src/main/cc/emul/dpi.cc
  sim/midas/src/main/cc/emul/mm.cc
  sim/midas/src/main/cc/emul/mm.h
  sim/midas/src/main/cc/emul/mmio.h
  sim/midas/src/main/cc/simif.cc
  sim/midas/src/main/cc/simif.h
  sim/midas/src/main/cc/simif_emul.cc
  sim/midas/src/main/cc/simif_emul.h
  sim/midas/src/main/cc/simif_emul_vcs.cc
  sim/midas/src/main/cc/simif_emul_vcs.h
  sim/midas/src/main/cc/simif_emul_verilator.cc
  sim/midas/src/main/cc/simif_emul_verilator.h
  sim/midas/src/main/cc/simif_f1.cc
  sim/midas/src/main/cc/simif_f1.h
  sim/midas/src/main/cc/simif_vitis.cc
  sim/midas/src/main/cc/simif_vitis.h
  sim/midas/src/main/scala/midas/core/FPGATop.scala
  sim/midas/src/main/scala/midas/platform/PlatformShim.scala
  sim/midas/src/main/scala/midas/widgets/LoadMem.scala
  sim/midas/src/main/verilog/top.sv
Labels: changelog:omit

#1355 Split TutorialSuite into multiple files and helpers
  sim/firesim-lib/src/test/scala/TestSuiteCommon.scala
  sim/firesim-lib/src/test/scala/TestSuiteUtil.scala
  sim/src/test/scala/bridges/BridgeSuite.scala
  sim/src/test/scala/fasedtests/FASEDTestSuite.scala
  sim/src/test/scala/firesim/FireSimTestSuite.scala
  sim/src/test/scala/midasexamples/AssertSuite.scala
  sim/src/test/scala/midasexamples/AutoCounterSuite.scala
  sim/src/test/scala/midasexamples/ChiselExampleDesigns.scala
  sim/src/test/scala/midasexamples/FMRSuite.scala
  sim/src/test/scala/midasexamples/GoldenGateMiscSuite.scala
  sim/src/test/scala/midasexamples/PlusArgSuite.scala
  sim/src/test/scala/midasexamples/PrintfSuite.scala
  sim/src/test/scala/midasexamples/ResetPulseSuite.scala
  sim/src/test/scala/midasexamples/TutorialSuite.scala
  sim/src/test/scala/unittest/UnitTestSuite.scala
Labels: changelog:omit

#1342 Introduced a uniform harness across all simulations
  sim/midas/src/main/cc/simif.cc
  sim/midas/src/main/cc/simif.h
  sim/src/main/cc/bridges/BridgeHarness.cc
  sim/src/main/cc/fasedtests/fasedtests_top.cc
  sim/src/main/cc/fasedtests/fasedtests_top.h
  sim/src/main/cc/firesim/firesim_top.cc
  sim/src/main/cc/firesim/firesim_top.h
  sim/src/main/cc/midasexamples/TestHarness.cc
Labels: changelog:changed, ci:fpga-deploy

#1359 Moved constructor macros to the constructor header
  sim/firesim-lib/src/main/cc/bridges/blockdev.h
  sim/firesim-lib/src/main/cc/bridges/serial.h
  sim/firesim-lib/src/main/cc/bridges/simplenic.h
  sim/firesim-lib/src/main/cc/bridges/tracerv.h
  sim/firesim-lib/src/main/cc/bridges/uart.h
  sim/midas/src/main/cc/bridges/autocounter.h
  sim/midas/src/main/cc/bridges/fased_memory_timing_model.h
  sim/midas/src/main/cc/bridges/plusargs.h
  sim/midas/src/main/cc/bridges/reset_pulse.h
  sim/midas/src/main/cc/bridges/synthesized_assertions.h
  sim/midas/src/main/cc/bridges/synthesized_prints.h
  sim/midas/src/main/cc/bridges/termination.h
  sim/midas/src/main/cc/constructor.h
  sim/src/main/cc/firesim/firesim_top.cc
  sim/src/main/cc/firesim/firesim_top.h
Labels: changelog:omit

#1367 Eliminate random number generation from simif
  sim/midas/src/main/cc/simif.cc
  sim/midas/src/main/cc/simif.h
  sim/midas/src/main/cc/simif_emul.cc
  sim/midas/src/main/cc/simif_emul.h
  sim/src/main/cc/midasexamples/TestWireInterconnect.cc
  sim/src/test/scala/midasexamples/ChiselExampleDesigns.scala
Labels: changelog:omit

#1353 Split `target-agnostic.mk` into multiple files
  sim/Makefile
  sim/make/chipyard.mk
  sim/make/config.mk
  sim/make/driver.mk
  sim/make/fpga.mk
  sim/make/goldengate.mk
  sim/make/library.mk
  sim/make/scala.mk
  sim/make/unittest.mk
  sim/make/vcs.mk
  sim/make/verilator.mk
  sim/src/main/makefrag/bridges/Makefrag
  sim/src/main/makefrag/fasedtests/Makefrag
  sim/src/main/makefrag/firesim/Makefrag
  sim/src/main/makefrag/midasexamples/Makefrag
  sim/target-agnostic.mk
Labels: changelog:changed, ci:fpga-deploy

#1366 Stream Engine IO interfaces
  sim/firesim-lib/src/main/cc/bridges/simplenic.cc
  sim/firesim-lib/src/main/cc/bridges/simplenic.h
  sim/firesim-lib/src/main/cc/bridges/tracerv.cc
  sim/firesim-lib/src/main/cc/bridges/tracerv.h
  sim/midas/src/main/cc/bridges/bridge_driver.cc
  sim/midas/src/main/cc/bridges/bridge_driver.h
  sim/midas/src/main/cc/bridges/bridge_stream_driver.h
  sim/midas/src/main/cc/bridges/cpu_managed_stream.cc
  sim/midas/src/main/cc/bridges/cpu_managed_stream.h
  sim/midas/src/main/cc/bridges/fpga_managed_stream.cc
  sim/midas/src/main/cc/bridges/fpga_managed_stream.h
  sim/midas/src/main/cc/bridges/stream_engine.cc
  sim/midas/src/main/cc/bridges/stream_engine.h
  sim/midas/src/main/cc/bridges/synthesized_prints.cc
  sim/midas/src/main/cc/bridges/synthesized_prints.h
  sim/midas/src/main/cc/constructor.h
  sim/midas/src/main/cc/emul/dpi.cc
  sim/midas/src/main/cc/emul/mmio.cc
  sim/midas/src/main/cc/emul/mmio.h
  sim/midas/src/main/cc/simif.cc
  sim/midas/src/main/cc/simif.h
  sim/midas/src/main/cc/simif_emul.cc
  sim/midas/src/main/cc/simif_emul.h
  sim/midas/src/main/cc/simif_f1.cc
  sim/midas/src/main/cc/simif_f1.h
  sim/midas/src/main/cc/simif_vitis.cc
  sim/midas/src/main/cc/simif_vitis.h
Labels: changelog:omit, ci:fpga-deploy

#1373 Fix a memory leak in the serial bridge
  sim/firesim-lib/src/main/cc/bridges/serial.cc
  sim/firesim-lib/src/main/cc/bridges/serial.h
Labels: changelog:omit

#1371 Split timing functions from simif.h
  sim/midas/src/main/cc/bridges/timing.cc
  sim/midas/src/main/cc/bridges/timing.h
  sim/midas/src/main/cc/simif.cc
  sim/midas/src/main/cc/simif.h
Labels: changelog:omit

#1376 Fix Valgrind false positives
  sim/midas/src/main/cc/emul/dpi.cc
Labels: changelog:omit

#1372 Split simulation_t from simif.h
  sim/midas/src/main/cc/bridges/simulation.cc
  sim/midas/src/main/cc/bridges/simulation.h
  sim/midas/src/main/cc/simif.cc
  sim/midas/src/main/cc/simif.h
  sim/src/main/cc/bridges/BridgeHarness.h
  sim/src/main/cc/fasedtests/fasedtests_top.cc
  sim/src/main/cc/fasedtests/fasedtests_top.h
  sim/src/main/cc/firesim/firesim_top.h
  sim/src/main/cc/midasexamples/TestHarness.h
Labels: changelog:omit

#1379 Remove the use of DPI utilities from dpi.cc
  sim/midas/src/main/cc/Makefile
  sim/midas/src/main/cc/emul/dpi.cc
  sim/midas/src/main/scala/midas/platform/PlatformShim.scala
Labels: changelog:omit

#1299 Changed "firesim infrasetup" to deploy using a tarball.
  deploy/runtools/firesim_topology_elements.py
  deploy/runtools/firesim_topology_with_passes.py
  deploy/runtools/run_farm_deploy_managers.py
  deploy/runtools/runtime_config.py
  docs/Advanced-Usage/Manager/Manager-Configuration-Files.rst
Labels: changelog:changed

#1374 Separate XSIM from f1 into simif_xsim
  sim/Makefile
  sim/make/driver.mk
  sim/make/fpga.mk
  sim/make/xsim.mk
  sim/midas/src/main/cc/Makefile
  sim/midas/src/main/cc/simif_f1.cc
  sim/midas/src/main/cc/simif_f1_xsim.cc
Labels: changelog:omit

#1378 Fix Assorted Scala warnings
  sim/firesim-lib/src/main/scala/bridges/BlockDevBridge.scala
  sim/firesim-lib/src/main/scala/bridges/DromajoBridge.scala
  sim/firesim-lib/src/main/scala/bridges/SerialBridge.scala
  sim/firesim-lib/src/main/scala/bridges/SimpleNICBridge.scala
  sim/firesim-lib/src/main/scala/bridges/TracerVBridge.scala
  sim/midas/src/main/scala/midas/core/Channel.scala
  sim/midas/src/main/scala/midas/core/SimWrapper.scala
  sim/midas/src/main/scala/midas/models/dram/BankConflictModel.scala
  sim/midas/src/main/scala/midas/models/dram/DramCommon.scala
  sim/midas/src/main/scala/midas/models/dram/EgressUnit.scala
  sim/midas/src/main/scala/midas/models/dram/FASEDMemoryTimingModel.scala
  sim/midas/src/main/scala/midas/models/dram/FIFOMASModel.scala
  sim/midas/src/main/scala/midas/models/dram/FRFCFSModel.scala
  sim/midas/src/main/scala/midas/models/dram/LastLevelCache.scala
  sim/midas/src/main/scala/midas/models/dram/LatencyBandwidthPipe.scala
  sim/midas/src/main/scala/midas/models/dram/RuntimeConfGenerator.scala
  sim/midas/src/main/scala/midas/models/dram/TimingModel.scala
  sim/midas/src/main/scala/midas/models/dram/Util.scala
  sim/midas/src/main/scala/midas/passes/AnnotationWiringTransform.scala
  sim/midas/src/main/scala/midas/passes/AssertionSynthesis.scala
  sim/midas/src/main/scala/midas/passes/AutoCounterTransform.scala
  sim/midas/src/main/scala/midas/passes/BridgeTopWiring.scala
  sim/midas/src/main/scala/midas/passes/TriggerWiring.scala
  sim/midas/src/main/scala/midas/passes/Utils.scala
  sim/midas/src/main/scala/midas/passes/fame/Annotations.scala
  sim/midas/src/main/scala/midas/passes/fame/EmitAndWrapRAMModels.scala
  sim/midas/src/main/scala/midas/platform/PlatformShim.scala
  sim/midas/src/main/scala/midas/widgets/AXI4TieOff.scala
  sim/midas/src/main/scala/midas/widgets/AssertBridge.scala
  sim/midas/src/main/scala/midas/widgets/AutoCounterBridge.scala
  sim/midas/src/main/scala/midas/widgets/Bridge.scala
  sim/midas/src/main/scala/midas/widgets/BridgeAnnotations.scala
  sim/midas/src/main/scala/midas/widgets/ChannelizedHostPort.scala
  sim/midas/src/main/scala/midas/widgets/ClockBridge.scala
  sim/midas/src/main/scala/midas/widgets/HostPort.scala
  sim/midas/src/main/scala/midas/widgets/Lib.scala
  sim/midas/src/main/scala/midas/widgets/PrintBridge.scala
  sim/midas/src/main/scala/midas/widgets/ResetPulseBridge.scala
  sim/midas/src/main/scala/midas/widgets/SerializationUtils.scala
  sim/midas/src/main/scala/midas/widgets/TerminationBridge.scala
  sim/midas/src/main/scala/midas/widgets/Widget.scala
  sim/midas/targetutils/src/main/scala/midas/annotations.scala
Labels: changelog:fixed

#1384 Re-enable compilation of the Dromajo bridge
  sim/firesim-lib/src/main/cc/bridges/dromajo.cc
  sim/firesim-lib/src/main/cc/bridges/dromajo.h
  sim/midas/src/main/cc/core/constructor.h
Labels: changelog:omit

#1354 Split project `Makefrag` into multiple components
  docs/Golden-Gate/Bridge-Walkthrough.rst
  sim/Makefile
  sim/make/config.mk
  sim/src/main/makefrag/bridges/Makefrag
  sim/src/main/makefrag/bridges/build.mk
  sim/src/main/makefrag/bridges/config.mk
  sim/src/main/makefrag/bridges/driver.mk
  sim/src/main/makefrag/bridges/metasim.mk
  sim/src/main/makefrag/fasedtests/Makefrag
  sim/src/main/makefrag/fasedtests/build.mk
  sim/src/main/makefrag/fasedtests/config.mk
  sim/src/main/makefrag/fasedtests/driver.mk
  sim/src/main/makefrag/fasedtests/metasim.mk
  sim/src/main/makefrag/firesim/build.mk
  sim/src/main/makefrag/firesim/config.mk
  sim/src/main/makefrag/firesim/driver.mk
  sim/src/main/makefrag/firesim/metasim.mk
  sim/src/main/makefrag/midasexamples/Makefrag
  sim/src/main/makefrag/midasexamples/build.mk
  sim/src/main/makefrag/midasexamples/config.mk
  sim/src/main/makefrag/midasexamples/driver.mk
  sim/src/main/makefrag/midasexamples/metasim.mk
Labels: changelog:changed, ci:fpga-deploy

#1394 Fixed platform configs not being applied
  sim/src/test/scala/firesim/FireSimTestSuite.scala
Labels: changelog:fixed

#1344 Fix Vitis CI
  .github/scripts/run-linux-poweroff-vitis.py
  .github/scripts/vitis-test/config_build_recipes.yaml
  .github/scripts/vitis-test/config_hwdb.yaml
  .github/scripts/vitis-test/config_runtime.yaml
  .github/workflows/firesim-run-tests.yml
  sim/make/driver.mk
Labels: changelog:fixed, ci:fpga-deploy

#1390 Cache the classpath between SBT runs
  sim/Makefile
  sim/make/chipyard.mk
  sim/make/config.mk
  sim/make/goldengate.mk
  sim/make/scala-build.mk
  sim/src/main/makefrag/bridges/build.mk
  sim/src/main/makefrag/fasedtests/build.mk
  sim/src/main/makefrag/fasedtests/config.mk
  sim/src/main/makefrag/firesim/build.mk
  sim/src/main/makefrag/firesim/config.mk
  sim/src/main/makefrag/midasexamples/build.mk
Labels: changelog:added

#1385 Switch to py script for XRT shell flashing
  platforms/vitis/scripts/flash-xdma-shells.py
  platforms/vitis/scripts/flash-xdma-shells.sh
Labels: changelog:changed

#1382 Added a root widget class and a low-overhead RTTI mechanism
  sim/firesim-lib/src/main/cc/bridges/blockdev.cc
  sim/firesim-lib/src/main/cc/bridges/blockdev.h
  sim/firesim-lib/src/main/cc/bridges/dromajo.cc
  sim/firesim-lib/src/main/cc/bridges/dromajo.h
  sim/firesim-lib/src/main/cc/bridges/groundtest.cc
  sim/firesim-lib/src/main/cc/bridges/groundtest.h
  sim/firesim-lib/src/main/cc/bridges/serial.cc
  sim/firesim-lib/src/main/cc/bridges/serial.h
  sim/firesim-lib/src/main/cc/bridges/simplenic.cc
  sim/firesim-lib/src/main/cc/bridges/simplenic.h
  sim/firesim-lib/src/main/cc/bridges/tracerv.cc
  sim/firesim-lib/src/main/cc/bridges/tracerv.h
  sim/firesim-lib/src/main/cc/bridges/uart.cc
  sim/firesim-lib/src/main/cc/bridges/uart.h
  sim/midas/src/main/cc/bridges/autocounter.cc
  sim/midas/src/main/cc/bridges/autocounter.h
  sim/midas/src/main/cc/bridges/clock.cc
  sim/midas/src/main/cc/bridges/clock.h
  sim/midas/src/main/cc/bridges/fased_memory_timing_model.cc
  sim/midas/src/main/cc/bridges/fased_memory_timing_model.h
  sim/midas/src/main/cc/bridges/heartbeat.cc
  sim/midas/src/main/cc/bridges/heartbeat.h
  sim/midas/src/main/cc/bridges/loadmem.cc
  sim/midas/src/main/cc/bridges/loadmem.h
  sim/midas/src/main/cc/bridges/master.cc
  sim/midas/src/main/cc/bridges/master.h
  sim/midas/src/main/cc/bridges/peek_poke.cc
  sim/midas/src/main/cc/bridges/peek_poke.h
  sim/midas/src/main/cc/bridges/plusargs.cc
  sim/midas/src/main/cc/bridges/plusargs.h
  sim/midas/src/main/cc/bridges/reset_pulse.cc
  sim/midas/src/main/cc/bridges/reset_pulse.h
  sim/midas/src/main/cc/bridges/synthesized_assertions.cc
  sim/midas/src/main/cc/bridges/synthesized_assertions.h
  sim/midas/src/main/cc/bridges/synthesized_prints.cc
  sim/midas/src/main/cc/bridges/synthesized_prints.h
  sim/midas/src/main/cc/bridges/termination.cc
  sim/midas/src/main/cc/bridges/termination.h
  sim/midas/src/main/cc/core/bridge_driver.cc
  sim/midas/src/main/cc/core/bridge_driver.h
  sim/midas/src/main/cc/core/constructor.h
  sim/midas/src/main/cc/core/simif.cc
  sim/midas/src/main/cc/core/widget.cc
  sim/midas/src/main/cc/core/widget.h
  sim/src/main/cc/fasedtests/fasedtests_top.cc
  sim/src/main/cc/fasedtests/test_harness_bridge.cc
  sim/src/main/cc/fasedtests/test_harness_bridge.h
  sim/src/main/cc/firesim/firesim_top.cc
  sim/src/main/cc/midasexamples/AssertTest.h
Labels: changelog:added

#1395 Fixes for Chisel 3.6 support
  sim/firesim-lib/src/main/scala/passes/AsyncResetReg.scala
  sim/midas/src/main/scala/midas/FPGAQoRShimGenerator.scala
  sim/midas/src/main/scala/midas/models/sram/AsyncMemModel.scala
  sim/midas/src/main/scala/midas/models/sram/RegfileModel.scala
  sim/midas/src/test/scala/midas/widgets/ChannelizedHostPortIOSpec.scala
  sim/src/main/scala/midasexamples/AssertModule.scala
  sim/src/main/scala/midasexamples/PrintfModule.scala
  sim/src/main/scala/midasexamples/TriggerPredicatedPrintf.scala
  sim/src/main/scala/midasexamples/TriggerWiringModule.scala
  sim/src/main/scala/midasexamples/TrivialMulticlock.scala
  sim/src/main/scala/midasexamples/WireInterconnect.scala
Labels: changelog:fixed

#1369 Added a bridge registry to own all bridge instances
  .clang-tidy
  docs/Golden-Gate/Bridge-Walkthrough.rst
  sim/make/cpp-lint.mk
  sim/midas/src/main/cc/bridges/cpu_managed_stream.cc
  sim/midas/src/main/cc/bridges/cpu_managed_stream.h
  sim/midas/src/main/cc/bridges/fpga_managed_stream.cc
  sim/midas/src/main/cc/bridges/fpga_managed_stream.h
  sim/midas/src/main/cc/core/constructor.h
  sim/midas/src/main/cc/core/simif.cc
  sim/midas/src/main/cc/core/simif.h
  sim/midas/src/main/cc/core/widget_registry.cc
  sim/midas/src/main/cc/core/widget_registry.h
  sim/midas/src/main/cc/emul/simif_emul.cc
  sim/midas/src/main/cc/emul/simif_emul.h
  sim/midas/src/main/cc/simif_f1.cc
  sim/midas/src/main/cc/simif_f1_xsim.cc
  sim/midas/src/main/cc/simif_vitis.cc
  sim/src/main/cc/bridges/BridgeHarness.cc
  sim/src/main/cc/bridges/BridgeHarness.h
  sim/src/main/cc/fasedtests/fasedtests_top.cc
  sim/src/main/cc/firesim/firesim_top.cc
  sim/src/main/cc/midasexamples/AssertTest.h
  sim/src/main/cc/midasexamples/AutoCounterTest.h
  sim/src/main/cc/midasexamples/PassthroughModelTest.h
  sim/src/main/cc/midasexamples/PrintfTest.h
  sim/src/main/cc/midasexamples/TestAssertGlobalResetCondition.cc
  sim/src/main/cc/midasexamples/TestAssertModule.cc
  sim/src/main/cc/midasexamples/TestAssertTorture.cc
  sim/src/main/cc/midasexamples/TestAutoCounter32bRollover.cc
  sim/src/main/cc/midasexamples/TestAutoCounterCoverModule.cc
  sim/src/main/cc/midasexamples/TestAutoCounterGlobalResetCondition.cc
  sim/src/main/cc/midasexamples/TestAutoCounterModule.cc
  sim/src/main/cc/midasexamples/TestAutoCounterPrintfModule.cc
  sim/src/main/cc/midasexamples/TestGCD.cc
  sim/src/main/cc/midasexamples/TestHarness.cc
  sim/src/main/cc/midasexamples/TestHarness.h
  sim/src/main/cc/midasexamples/TestMultiSRAM.cc
  sim/src/main/cc/midasexamples/TestMulticlockAssertModule.cc
  sim/src/main/cc/midasexamples/TestNarrowPrintfModule.cc
  sim/src/main/cc/midasexamples/TestPlusArgsModule.cc
  sim/src/main/cc/midasexamples/TestPrintfCycleBounds.cc
  sim/src/main/cc/midasexamples/TestPrintfModule.cc
  sim/src/main/cc/midasexamples/TestResetPulseBridgeTest.cc
  sim/src/main/cc/midasexamples/TestTerminationModule.cc
  sim/src/main/cc/midasexamples/TestTerminationModuleAssert.cc
  sim/src/main/cc/midasexamples/TestTriggerPredicatedPrintf.cc
  sim/src/main/cc/midasexamples/TestTriggerWiringModule.cc
Labels: changelog:added

#1399 Moved simulation step control to the PeekPoke bridge
  deploy/sample-backup-configs/sample_config_hwdb.yaml
  sim/midas/src/main/cc/bridges/master.cc
  sim/midas/src/main/cc/bridges/master.h
  sim/midas/src/main/cc/bridges/peek_poke.cc
  sim/midas/src/main/cc/bridges/peek_poke.h
  sim/midas/src/main/cc/core/simif.h
  sim/midas/src/main/scala/midas/core/FPGATop.scala
  sim/midas/src/main/scala/midas/widgets/Master.scala
  sim/midas/src/main/scala/midas/widgets/PeekPokeIO.scala
  sim/midas/src/main/scala/midas/widgets/Pulsify.scala
  sim/src/main/cc/bridges/BridgeHarness.cc
  sim/src/main/cc/fasedtests/fasedtests_top.cc
  sim/src/main/cc/firesim/firesim_top.cc
  sim/src/main/cc/midasexamples/AutoCounterTest.h
  sim/src/main/cc/midasexamples/PrintfTest.h
  sim/src/main/cc/midasexamples/TestAssertGlobalResetCondition.cc
  sim/src/main/cc/midasexamples/TestAssertModule.cc
  sim/src/main/cc/midasexamples/TestAssertTorture.cc
  sim/src/main/cc/midasexamples/TestHarness.cc
  sim/src/main/cc/midasexamples/TestMulticlockAssertModule.cc
  sim/src/main/cc/midasexamples/TestTerminationModuleAssert.cc
  sim/src/main/cc/midasexamples/TestTriggerWiringModule.cc
Labels: changelog:changed, ci:fpga-deploy

#1401 Fix loadmem bug in firesim_tsi.cc
  sim/firesim-lib/src/main/cc/fesvr/firesim_tsi.h
Labels: bug, changelog:fixed

#1408 Fix incremental builds triggered by scala changes
  sim/make/scala-build.mk
  sim/midas/src/main/scala/midas/widgets/Master.scala
Labels: changelog:fixed

#1411 Add workshop info to README.md
  README.md
Labels: changelog:omit

#1409 Fix Vitis driver compilation + Fix CY-as-top driver builds
  sim/make/goldengate.mk
  sim/make/scala-build.mk
  sim/midas/src/main/cc/simif_f1.cc
  sim/midas/src/main/cc/simif_f1_xsim.cc
  sim/midas/src/main/cc/simif_vitis.cc
  sim/src/main/makefrag/firesim/build.mk
  sim/src/main/makefrag/firesim/config.mk
Labels: ci:fpga-deploy

#1412 Add reports and checkpoints section to vitis readme
  platforms/vitis/README.md
Labels: changelog:added
