Repository firesim/firesim, pull requests merged in 2023-08, with the labels that each got.

#1621 Fix doc substitution
  docs/Getting-Started-Guides/AWS-EC2-F1-Getting-Started/Initial-Setup/Configuring-Required-Infrastructure-in-Your-AWS-Account.rst
Labels: changelog:fixed

#1623 Switch to different AWS CI account
  .github/workflows/firesim-cleanup.yml
  .github/workflows/firesim-publish-scala-doc.yml
  .github/workflows/firesim-run-tests.yml
  deploy/awstools/awstools.py
Labels: changelog:omit, ci:fpga-deploy

#1627 Small whitespace fixes + AGFI/FI rebuild
  .github/workflows/firesim-publish-scala-doc.yml
  deploy/sample-backup-configs/sample_config_hwdb.yaml
  sim/midas/src/main/scala/midas/FPGAQoRShimGenerator.scala
  sim/midas/src/main/scala/midas/core/CPUManagedStreamEngine.scala
  sim/midas/src/main/scala/midas/core/SimWrapper.scala
  sim/midas/src/main/scala/midas/passes/AnnotationWiringTransform.scala
  sim/midas/src/main/scala/midas/passes/EnsureNoTargetIO.scala
  sim/midas/src/main/scala/midas/passes/HoistStopAndPrintfEnables.scala
  sim/midas/src/main/scala/midas/passes/HostClockAnnotation.scala
  sim/midas/src/main/scala/midas/passes/MidasTransforms.scala
  sim/midas/src/main/scala/midas/passes/PrintSynthesis.scala
  sim/midas/src/main/scala/midas/passes/SimulationMapping.scala
  sim/midas/src/main/scala/midas/passes/TargetClockAnalysis.scala
  sim/midas/src/main/scala/midas/passes/package.scala
Labels: changelog:omit

#1631 Fix publish scala docs
  .github/actions/buildsetup/action.yml
  .github/workflows/firesim-publish-scala-doc.yml
Labels: changelog:fixed

#1635 Remove GenericParameterizedBundle (not needed with new chisel)
  sim/midas/src/main/scala/midas/models/dram/DramCommon.scala
Labels: changelog:omit

#1632 add missing step for flashing local FPGAs
  docs/Getting-Started-Guides/On-Premises-FPGA-Getting-Started/Initial-Setup/Xilinx-XDMA-Template.rst
Labels: changelog:fixed

#1636 Add header guards to TraceRV code
  sim/firesim-lib/src/main/cc/bridges/tracerv/trace_tracker.h
  sim/firesim-lib/src/main/cc/bridges/tracerv/tracerv_processing.h
Labels: changelog:omit

#1640 Don't translate to json in workflow monitor to prevent error
  .github/scripts/workflow-monitor.py
Labels: changelog:fixed

#1549 fix kill pass terminate condition
  deploy/runtools/firesim_topology_with_passes.py
Labels: changelog:fixed

#1596 Expand TracerV to support more than 7 IPC with FMR fix
  deploy/sample-backup-configs/sample_config_hwdb.yaml
  sim/firesim-lib/src/main/cc/bridges/tracerv.cc
  sim/firesim-lib/src/main/cc/bridges/tracerv.h
  sim/firesim-lib/src/main/scala/bridges/TracerVBridge.scala
  sim/src/main/cc/bridges/TracerVModule.cc
  sim/src/main/scala/bridges/TracerVModule.scala
  sim/src/test/scala/bridges/TracerVSuite.scala
Labels: changelog:added, ci:fpga-deploy

#1643 TracerV binary mode - Print cycle + insts only (no padding)
  sim/firesim-lib/src/main/cc/bridges/tracerv.cc
Labels: changelog:changed
