Repository firesim/firesim, pull requests merged in 2024-09, with the labels that each got.

#1821 Bump to newer version of Chipyard with fixes (in docs)
  docs/conf.py
Labels: changelog:changed

#1822 Fix metasimulations
  deploy/runtools/runtime_config.py
Labels: changelog:fixed

#1824 1.20.1 Fixes
  deploy/awstools/awstools.py
  deploy/workloads/br-base-flamegraph.json
  deploy/workloads/br-base-non-uniform.json
  deploy/workloads/br-base-uniform.json
Labels: changelog:fixed

#1823 Simple counter example (clock + reset + max-cycle timeout)
  .github/workflows/berkeley-cluster-tests-1.yml
  .github/workflows/berkeley-cluster-tests-2.yml
  conda-reqs/conda-reqs.conda-lock.yml
  conda-reqs/docs.yaml
  docs/Advanced-Usage/FireSim-without-Chipyard.rst
  docs/conf.py
  scripts/generate-conda-lockfile.sh
  sim/src/main/cc/examples/simple_counter_top.cc
  sim/src/main/makefrag/examples/build.mk
  sim/src/main/makefrag/examples/config.mk
  sim/src/main/makefrag/examples/driver.mk
  sim/src/main/makefrag/examples/metasim.mk
  sim/src/main/scala/examples/SimpleCounter.scala
Labels: changelog:added
