Repository firesim/firesim, pull requests merged in 2024-03, with the labels that each got.

#1696 Bump to gcc 13
  conda-reqs/conda-reqs.conda-lock.yml
  conda-reqs/firesim.yaml
  sim/midas/src/main/cc/core/address_map.h
Labels: changelog:changed

#1701 Update AWS EC2 F1 region list
  deploy/awstools/afitools.py
  docs/Getting-Started-Guides/AWS-EC2-F1-Getting-Started/Initial-Setup/Configuring-Required-Infrastructure-in-Your-AWS-Account.rst
  docs/Getting-Started-Guides/AWS-EC2-F1-Getting-Started/Initial-Setup/Setting-up-your-Manager-Instance.rst
Labels: changelog:added

#1704 Add initial implementation of variable FESVR rate during loading phase of simulation
  sim/firesim-lib/src/main/cc/bridges/tsibridge.cc
  sim/firesim-lib/src/main/cc/bridges/tsibridge.h
  sim/firesim-lib/src/main/cc/fesvr/firesim_tsi.cc
  sim/firesim-lib/src/main/cc/fesvr/firesim_tsi.h
Labels: changelog:added

#1709 Bump CI versions to avoid Node16 warnings
  .github/workflows/firesim-aws-run-tests.yml
  .github/workflows/firesim-cleanup.yml
  .github/workflows/firesim-non-aws-run-tests.yml
  .github/workflows/firesim-publish-scala-doc.yml
  .github/workflows/release-notes.yml
Labels: changelog:omit
